import type { EnemyEntity, PlayerState, SphereEntity } from '../engine';
const TAU=Math.PI*2,BASE='#8ef0ff',WHITE='#ffffff',RESONANCE='#ffd166',DISABLED='#ff4d70',LINE=1.7,RX=2.05,RY=.55;
type VisualState={lastTime:number,lastAura:number,attack:number,resonance:number,phase:number};
const STATES=new WeakMap<SphereEntity,VisualState>(),GRADIENTS=new WeakMap<CanvasRenderingContext2D,Map<number,CanvasGradient>>();
function stateOf(s:SphereEntity):VisualState{let v=STATES.get(s);if(v)return v;v={lastTime:0,lastAura:Number.isFinite(s.auraTimer)?s.auraTimer:0,attack:0,resonance:0,phase:((s.pos.x*.011+s.pos.y*.007)%TAU+TAU)%TAU};STATES.set(s,v);return v}
function cache(c:CanvasRenderingContext2D){let m=GRADIENTS.get(c);if(m)return m;m=new Map<number,CanvasGradient>();GRADIENTS.set(c,m);return m}
function glow(c:CanvasRenderingContext2D,mode:number){const old=cache(c).get(mode);if(old)return old;const g=c.createRadialGradient(0,0,0,0,0,1);if(mode===1){g.addColorStop(0,'rgba(255,209,102,.70)');g.addColorStop(.18,'rgba(255,209,102,.38)');g.addColorStop(.52,'rgba(255,209,102,.12)');g.addColorStop(1,'rgba(255,209,102,0)')}else if(mode===2){g.addColorStop(0,'rgba(255,77,112,.62)');g.addColorStop(.18,'rgba(255,77,112,.34)');g.addColorStop(.52,'rgba(255,77,112,.12)');g.addColorStop(1,'rgba(255,77,112,0)')}else{g.addColorStop(0,'rgba(255,255,255,.78)');g.addColorStop(.16,'rgba(142,240,255,.46)');g.addColorStop(.52,'rgba(142,240,255,.15)');g.addColorStop(1,'rgba(142,240,255,0)')}cache(c).set(mode,g);return g}
function ox(a:number,r:number){return Math.cos(a)*r*RX}function oy(a:number,r:number){return Math.sin(a)*r*RY}
function orbit(c:CanvasRenderingContext2D,r:number,color:string,a:number){c.globalAlpha=a;c.strokeStyle=color;c.lineWidth=LINE*2.05;c.beginPath();c.ellipse(0,0,r*RX,r*RY,0,0,TAU);c.stroke();c.globalAlpha=Math.min(1,a+.18);c.lineWidth=LINE;c.beginPath();c.ellipse(0,0,r*RX,r*RY,0,0,TAU);c.stroke()}
function satellite(c:CanvasRenderingContext2D,x:number,y:number,size:number,color:string,a:number,rot:number){c.save();c.translate(x,y);c.rotate(rot);c.globalAlpha=a;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.moveTo(0,-size);c.lineTo(size*.72,0);c.lineTo(0,size);c.lineTo(-size*.72,0);c.closePath();c.stroke();c.fillStyle=WHITE;c.beginPath();c.arc(0,0,Math.max(1.1,size*.17),0,TAU);c.fill();c.restore()}
function drawGlow(c:CanvasRenderingContext2D,r:number,mode:number,a:number){c.save();c.globalAlpha=a;c.fillStyle=glow(c,mode);c.scale(r,r);c.beginPath();c.arc(0,0,1,0,TAU);c.fill();c.restore()}
function core(c:CanvasRenderingContext2D,r:number,mode:number,p:number,flash:number,disabled:boolean){const s=.97+p*.06;c.save();c.scale(s,s);c.save();c.globalAlpha=disabled?.08:.18+flash*.28;c.fillStyle=glow(c,mode);c.scale(r*1.75,r*1.75);c.beginPath();c.arc(0,0,1,0,TAU);c.fill();c.restore();const color=mode===1?RESONANCE:mode===2?DISABLED:BASE;c.globalAlpha=disabled?.25:.20;c.fillStyle=color;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.arc(0,0,r,0,TAU);c.fill();c.stroke();c.globalAlpha=disabled?.25:.94;c.fillStyle=WHITE;c.beginPath();c.arc(0,0,r*(.16+p*.016),0,TAU);c.fill();c.restore()}
function update(s:SphereEntity,p:PlayerState,t:number){const v=stateOf(s),dt=v.lastTime>0?Math.min(.05,Math.max(0,t-v.lastTime)):0;v.lastTime=t;const disabled=s.networkDisabledTimer>0||!s.alive;if(!disabled){const aura=Number.isFinite(s.auraTimer)?s.auraTimer:0;if(aura>v.lastAura+.12)v.attack=.30;v.lastAura=aura;v.attack=Math.max(0,v.attack-dt);if(p?.resonanceEventActive)v.resonance=1.4;v.resonance=Math.max(0,v.resonance-dt)}return v}
export function renderOrbitalSphereRuntimeVfx(c:CanvasRenderingContext2D,s:SphereEntity,p:PlayerState,time:number,scale=1,enemies:EnemyEntity[]=[]):void{if(!c||!s)return;const v=update(s,p,time),disabled=s.networkDisabledTimer>0||!s.alive,resonance=!disabled&&v.resonance>0,branch=p?.sphereBranches?.orbital,mode=disabled?2:resonance?1:0,color=mode===2?DISABLED:mode===1?RESONANCE:BASE,animationTime=disabled?0:time,pulse=disabled?.5:.5+.5*Math.sin(time*3.2+v.phase),r=24*scale,speed=branch==='orbital_dance'?.72:branch==='orbital_halo'?.28:branch==='orbital_blade'?.50:.42,flash=disabled?0:Math.max(0,1-v.attack/.30),phase=animationTime*speed+v.phase,tier=Math.max(1,Math.min(7,s.visualTier||1));
c.save();c.translate(s.pos.x,s.pos.y);c.globalCompositeOperation='lighter';drawGlow(c,r*1.65,mode,disabled?.08:.18);c.restore();
c.save();c.translate(s.pos.x,s.pos.y);c.globalCompositeOperation='source-over';c.rotate(animationTime*(branch==='orbital_halo'?.10:.22)+v.phase*.08);orbit(c,r,color,disabled?.16:resonance?.70:.72);
if(!disabled)for(let i=0;i<tier;i++){const a=phase+i*TAU/tier,d=Math.sin(a);satellite(c,ox(a,r),oy(a,r),r*(.19+(d+1)*.025),color,d<0?.38:.98,a+Math.PI/4)}
if(v.attack>0&&!disabled){const q=1-v.attack/.30,current=phase+(1-Math.pow(1-q,3))*.90,sx=ox(current,r),sy=oy(current,r);c.strokeStyle=color;c.lineWidth=LINE;for(let i=4;i>=1;i--){const a=current-i*.08;c.globalAlpha=.70*(1-q)/i;c.beginPath();c.moveTo(ox(a,r),oy(a,r));c.lineTo(sx,sy);c.stroke()}let ix=sx,iy=sy,near=Number.POSITIVE_INFINITY;for(const e of enemies){if(!e||e.hp<=0)continue;const dx=e.pos.x-s.pos.x-sx,dy=e.pos.y-s.pos.y-sy,d=Math.hypot(dx,dy);if(d<near&&d<=r*1.2){near=d;ix=sx+dx;iy=sy+dy}}c.globalAlpha=.86*(1-q);c.fillStyle=WHITE;c.beginPath();c.arc(ix,iy,r*.08,0,TAU);c.fill()}
c.globalAlpha=1;core(c,r*.72,mode,pulse,flash,disabled);if(disabled){c.globalAlpha=.38;c.strokeStyle=DISABLED;c.lineWidth=LINE;c.beginPath();c.moveTo(-r*.8,-r*.8);c.lineTo(r*.8,r*.8);c.moveTo(r*.8,-r*.8);c.lineTo(-r*.8,r*.8);c.stroke()}c.restore()}
export default renderOrbitalSphereRuntimeVfx;