import type { PlayerState, SphereEntity } from '../engine';
const TAU=Math.PI*2,BASE='#55dfff',WHITE='#ffffff',RESONANCE='#ffd166',DISABLED='#ff4d70',LINE=1.7;
const GRADIENTS=new WeakMap<CanvasRenderingContext2D,Map<number,CanvasGradient>>();
function cache(c:CanvasRenderingContext2D){let m=GRADIENTS.get(c);if(m)return m;m=new Map<number,CanvasGradient>();GRADIENTS.set(c,m);return m}
function glow(c:CanvasRenderingContext2D,mode:number){const old=cache(c).get(mode);if(old)return old;const g=c.createRadialGradient(0,0,0,0,0,1);if(mode===1){g.addColorStop(0,'rgba(255,209,102,.70)');g.addColorStop(.18,'rgba(255,209,102,.38)');g.addColorStop(.52,'rgba(255,209,102,.12)');g.addColorStop(1,'rgba(255,209,102,0)')}else if(mode===2){g.addColorStop(0,'rgba(255,77,112,.62)');g.addColorStop(.18,'rgba(255,77,112,.34)');g.addColorStop(.52,'rgba(255,77,112,.12)');g.addColorStop(1,'rgba(255,77,112,0)')}else{g.addColorStop(0,'rgba(255,255,255,.78)');g.addColorStop(.16,'rgba(85,223,255,.46)');g.addColorStop(.52,'rgba(85,223,255,.15)');g.addColorStop(1,'rgba(85,223,255,0)')}cache(c).set(mode,g);return g}
function finalIndex(p:PlayerState){const e=p.evolutions||[];for(const id of e){if(!id.startsWith('sphere:standard:7:'))continue;if(id.endsWith(':0'))return 0;if(id.endsWith(':1'))return 1;if(id.endsWith(':2'))return 2}return -1}
function diamond(c:CanvasRenderingContext2D,x:number,y:number,s:number,color:string,a:number){c.save();c.translate(x,y);c.globalAlpha=a;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.moveTo(0,-s);c.lineTo(s*.72,0);c.lineTo(0,s);c.lineTo(-s*.72,0);c.closePath();c.stroke();c.fillStyle=WHITE;c.beginPath();c.arc(0,0,Math.max(1,s*.16),0,TAU);c.fill();c.restore()}
function core(c:CanvasRenderingContext2D,r:number,mode:number,p:number,flash:number,disabled:boolean){const s=.97+p*.06;c.save();c.scale(s,s);c.save();c.globalAlpha=disabled?.08:.18+flash*.08;c.fillStyle=glow(c,mode);c.scale(r*1.75,r*1.75);c.beginPath();c.arc(0,0,1,0,TAU);c.fill();c.restore();const color=mode===1?RESONANCE:mode===2?DISABLED:BASE;c.globalAlpha=disabled?.25:.20;c.fillStyle=color;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.arc(0,0,r,0,TAU);c.fill();c.stroke();c.globalAlpha=disabled?.25:.94;c.fillStyle=WHITE;c.beginPath();c.arc(0,0,r*(.15+p*.015),0,TAU);c.fill();c.restore()}
function orbit(c:CanvasRenderingContext2D,r:number,color:string,rot:number,a:number){c.save();c.rotate(rot);c.strokeStyle=color;c.globalAlpha=a;c.lineWidth=LINE*2.05;c.beginPath();c.ellipse(0,0,r*1.22,r*.62,0,0,TAU);c.stroke();c.globalAlpha=Math.min(1,a+.18);c.lineWidth=LINE;c.beginPath();c.ellipse(0,0,r*1.22,r*.62,0,0,TAU);c.stroke();c.restore()}
function mutations(c:CanvasRenderingContext2D,p:PlayerState,s:SphereEntity,r:number,t:number,color:string,disabled:boolean){const b=p.sphereBranches?.standard,tier=Math.max(0,Math.min(7,s.visualTier||0)),a=disabled?.14:.38,f=finalIndex(p);if(b==='standard_resonator'){const w=(t*.72)%1;c.globalAlpha=a*(1-w);c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.ellipse(0,0,r*(1.35+w*.70),r*(.68+w*.35),0,0,TAU);c.stroke()}else if(b==='standard_singularity'){c.globalAlpha=a;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.arc(0,0,r*1.15,-t*.55,-t*.55+1.35);c.stroke();c.beginPath();c.arc(0,0,r*.91,-t*.55+Math.PI,-t*.55+Math.PI+1.35);c.stroke()}else if(b==='standard_swarm'){const n=Math.min(7,Math.max(3,tier+2));for(let i=0;i<n;i++){const q=t*.62+i*TAU/n;diamond(c,Math.cos(q)*r*1.46,Math.sin(q)*r*.76,r*.11,color,a)}}if(f===0){c.globalAlpha=disabled?.14:.34;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.arc(0,0,r*1.42,0,TAU);c.stroke()}else if(f===1){c.globalAlpha=disabled?.14:.34;c.strokeStyle=color;c.lineWidth=LINE;c.beginPath();c.moveTo(-r*1.28,0);c.lineTo(r*1.28,0);c.moveTo(0,-r*1.28);c.lineTo(0,r*1.28);c.stroke()}else if(f===2){for(let i=0;i<6;i++){const q=-t*.70+i*TAU/6;diamond(c,Math.cos(q)*r*1.44,Math.sin(q)*r*.86,r*.10,color,disabled?.14:.34)}}}
function attack(c:CanvasRenderingContext2D,s:SphereEntity,r:number,color:string,disabled:boolean){if(disabled||s.attackTimer<=0)return;const q=Math.max(0,Math.min(1,1-s.attackTimer/1.2)),reach=r*(1.05+q*.85);c.save();c.rotate(s.rotation||0);c.strokeStyle=color;c.lineWidth=LINE;for(let i=3;i>=1;i--){c.globalAlpha=(.18+(1-q)*.46)/i;c.beginPath();c.moveTo(r*(.42+i*.08),0);c.lineTo(reach-i*r*.10,0);c.stroke()}c.globalAlpha=.70*(1-q);c.fillStyle=WHITE;c.beginPath();c.arc(reach,0,r*.08,0,TAU);c.fill();c.restore()}
export function renderStandardSphereRuntimeVfx(c:CanvasRenderingContext2D,s:SphereEntity,p:PlayerState,time:number,scale=1):void{if(!c||!s)return;const disabled=s.networkDisabledTimer>0||!s.alive,resonance=!disabled&&Boolean(p?.resonanceEventActive),mode=disabled?2:resonance?1:0,color=mode===1?RESONANCE:mode===2?DISABLED:BASE,animationTime=disabled?0:time,pulse=disabled?.5:.5+.5*Math.sin(time*3.4+s.pos.x*.01),r=24*scale;c.save();c.translate(s.pos.x,s.pos.y);c.globalCompositeOperation='lighter';c.globalAlpha=disabled?.08:.18;c.fillStyle=glow(c,mode);c.scale(r*1.75,r*1.75);c.beginPath();c.arc(0,0,1,0,TAU);c.fill();c.restore();c.save();c.translate(s.pos.x,s.pos.y);c.globalCompositeOperation='source-over';orbit(c,r,color,animationTime*.22+s.pos.x*.001,disabled?.16:resonance?.70:.62);core(c,r*.72,mode,pulse,s.attackTimer>0?.65:0,disabled);mutations(c,p,s,r,animationTime,color,disabled);attack(c,s,r,color,disabled);c.restore()}
export default renderStandardSphereRuntimeVfx;