// Centralized run-balance constants. Gameplay values intentionally preserved from the current new-desing baseline.
export const BALANCE = {
  startingHp: 100,
  hpPerLevel: 6,
  firstLevelXp: 10,
  xpGrowthLinear: 3,
  xpGrowthQuadratic: 0.08,
  normalHpBase: 18,
  normalHpPerWave: 5.5,
  normalSpeedBase: 68,
  normalSpeedPerWave: 1.8,
  normalDamageBase: 7,
  normalDamagePerWave: 0.30,
  fastHpBase: 11,
  fastHpPerWave: 3.4,
  fastSpeedBase: 125,
  fastSpeedPerWave: 2.4,
  fastDamageBase: 8,
  fastDamagePerWave: 0.32,
  tankHpBase: 42,
  tankHpPerWave: 10.5,
  tankSpeedBase: 44,
  tankSpeedPerWave: 0.8,
  tankDamageBase: 11,
  tankDamagePerWave: 0.38,
  bossHpBase: 450,
  bossHpPerWave: 55,
  bossSpeedBase: 48,
  bossSpeedPerWave: 1.2,
  bossChargerSpeedBase: 72,
  bossChargerSpeedPerWave: 1.8,
  bossDamageBase: 28,
  bossDamagePerWave: 0.65,
  enemiesPerWaveBase: 4,
  enemiesPerWaveGrowth: 1.1,
} as const;
