import { type Difficulty } from './gameData';
import { loadCharacterId, loadCharacterProfiles } from './persistence';
import { createRunSeed, createRngState } from './rng';
import { BALANCE } from './engineBalance';
import { BASE_SPHERE_RADIUS, BASE_SPHERE_DAMAGE, BASE_SPHERE_DELAY } from './engineSpheres';
import { CHARACTER_DEFS, type CharacterId } from './characters';
import type { GameState, ShopState } from './engineTypes';

export interface LeaderEntry {
  name: string;
  time: number;
  wave: number;
  date: number;
}

export const BASE_PLAYER_SPEED = 180;
export const PLAYER_RADIUS = 16;
export const STELLA_LEGENDARY_CUTOFF_SECONDS = 25 * 60;

export function getXpToNextLevel(level: number): number {
  return Math.max(
    BALANCE.firstLevelXp,
    Math.round(
      BALANCE.firstLevelXp +
      Math.max(0, level - 1) * BALANCE.xpGrowthLinear +
      Math.pow(Math.max(0, level - 1), 2) * BALANCE.xpGrowthQuadratic
    ),
  );
}

export type MapTheme = 'parchment' | 'bamboo' | 'ocean' | 'sunset';

export const MAP_THEMES: { id: MapTheme; name: { ru: string; en: string } }[] = [
  { id: 'parchment', name: { ru: 'Свиток', en: 'Scroll' } },
  { id: 'bamboo', name: { ru: 'Бамбук', en: 'Bamboo' } },
  { id: 'ocean', name: { ru: 'Океан', en: 'Ocean' } },
  { id: 'sunset', name: { ru: 'Закат', en: 'Sunset' } },
];

export function createInitialState(
  shop: ShopState,
  playerName: string,
  difficulty: Difficulty = 'normal',
  mapTheme: MapTheme = 'parchment',
  runSeedOverride?: number,
): GameState {
  const runSeed = runSeedOverride === undefined ? createRunSeed(playerName, difficulty, mapTheme) : (runSeedOverride >>> 0) || 1;
  const rngState = createRngState(runSeed);
  const characterId = loadCharacterId();
  const profile = loadCharacterProfiles().find((item) => item.id === characterId);
  const characterMasteryLevel = profile?.masteryLevel || 1;
  const baseHp = BALANCE.startingHp + (shop.upgrades.hp || 0) * 10;
  const startHp = baseHp * getCharacterMaxHpMultiplierForId(characterId);
  const player: PlayerState = {
    pos: { x: 0, y: 0 },
    hp: startHp,
    maxHp: startHp,
    speed: BASE_PLAYER_SPEED,
    level: 1,
    xp: 0,
    xpToNext: BALANCE.firstLevelXp,
    abilities: {},
    activeAbilitySlots: 0,
    evolutions: [],
    artifacts: [],
    kills: 0,
    mutationStage: 0,
    invulnerableTimer: 0,
    contactDamageCooldown: 0,
    resonanceCharge: 0,
    resonanceEventActive: false,
    resonanceGeometryKey: 'none',
    resonanceGeometryNodes: [],
    resonanceLineBurst: 0,
    resonanceRingTimer: 0,
    resonanceRingPulseTimer: 0,
    resonanceRingCursor: 0,
    invulnUsed: false,
    shieldCharges: 0,
    shieldTimer: 0,
    dodgeTimer: 0,
    fireTrailTimer: 0,
    fireTrailCooldown: 0,
    blastCooldown: 0,
    teleportCooldown: 0,
    shieldCooldown: 0,
    minionCooldown: 0,
    lightningCooldown: 0,
    timestopCooldown: 0,
    darkritualCooldown: 0,
    overloadTimer: 0,
    timestopTimer: 0,
    swiftBootsTimer: 0,
    chaosOrbTimer: 0,
    chaosOrbBuff: null,
    chaosOrbBuffTimer: 0,
    teleportDamageBuffTimer: 0,
    fireCatalystTimer: 0,
    blinkHpCost: false,
    sphereXpAccumulator: 0,
    sphereUpgradeCount: 0,
    sphereProgression: { standard: 0, sniper: 0, shotgun: 0, chain: 0, aura: 0, orbital: 0, prism: 0, gravity: 0, pulse: 0, void: 0 },
    sphereBranches: {},
    sphereMods: { multishot: 0, pierce: 0, ricochet: 0, fire: 0, freeze: 0, poison: 0 },
    dashCooldown: 0,
    dashTimer: 0,
    dashDir: { x: 0, y: 0 },
    dashCount: 0,
    combo: 0,
    comboTimer: 0,
    comboMult: 1,
    buffTimer: 0,
    eliteKills: 0,
    chestOpens: 0,
    characterId,
    characterMasteryLevel,
    hunterMarkTarget: null,
    hunterMarkTimer: 0,
    hunterHitCount: 0,
    hunterHuntTarget: null,
    hunterHuntTimer: 0,
    hunterTrophyTimer: 0,
    engineerRelaySource: null,
    engineerRelayTimer: 0,
    alchemistCatalystTimer: 0,
  };
  return {
    player,
    spheres: [{
      pos: { x: 0, y: -95 },
      radius: BASE_SPHERE_RADIUS,
      damage: BASE_SPHERE_DAMAGE,
      attackDelay: BASE_SPHERE_DELAY,
      attackTimer: 0,
      rotation: 0,
      alive: true,
      networkDisabledTimer: 0,
      killsContribution: 0,
      formationHitCount: 0,
      resonancePulseTimer: 0,
      visualTier: 0,
      type: 'standard',
      auraTimer: 0,
    }],
    enemies: [],
    xpOrbs: [],
    healthPacks: [],
    particles: [],
    fireTrails: [],
    minions: [],
    lightnings: [],
    wave: 0,
    waveTimer: 3,
    waveEnemiesToSpawn: 0,
    waveSpawnTimer: 0,
    bossActive: false,
    bossDefeated: 0,
    time: 0,
    paused: false,
    gameOver: false,
    pendingUpgrade: null,
    levelUpPity: { ability: 0, sphere: 0, modifier: 0 },
    pendingArtifact: null,
    pendingStella: false,
    stellaClaims: 0,
    stellaLegendaryClaims: 0,
    stats: { time: 0, wave: 0, enemiesKilled: 0, goldEarned: 0 },
    screenShake: 0,
    bossArrow: null,
    flashText: null,
    keys: {},
    mouse: { x: 0, y: 0, down: false },
    formationMemory: null,
    worldWidth: 2400,
    worldHeight: 2400,
    mapTheme,
    camera: { x: 0, y: 0 },
    activeKeyMap: {},
    sphereProjectiles: [],
    artifactPickupPending: false,
    pendingSphereUpgrade: null,
    damageNumbers: [],
    chests: [],
    runes: [],
    difficulty: difficulty,
    evolutionsThisRun: 0,
    selectedSphereType: 'standard',
    shopUpgrades: { ...shop.upgrades },
    runSeed,
    rngState,
  };
}

export function createInitialState(
  shop: ShopState,
  playerName: string,
  difficulty: Difficulty = 'normal',
  mapTheme: MapTheme = 'parchment',
  runSeedOverride?: number,
): GameState {
  const runSeed = runSeedOverride === undefined ? createRunSeed(playerName, difficulty, mapTheme) : (runSeedOverride >>> 0) || 1;
  const rngState = createRngState(runSeed);
  const characterId = loadCharacterId();
  const profile = loadCharacterProfiles().find((item) => item.id === characterId);
  const characterMasteryLevel = profile?.masteryLevel || 1;
  const baseHp = BALANCE.startingHp + (shop.upgrades.hp || 0) * 10;
  const startHp = baseHp * getCharacterMaxHpMultiplierForId(characterId);
  const player: PlayerState = {
    pos: { x: 0, y: 0 },
    hp: startHp,
    maxHp: startHp,
    speed: BASE_PLAYER_SPEED,
    level: 1,
    xp: 0,
    xpToNext: BALANCE.firstLevelXp,
    abilities: {},
    activeAbilitySlots: 0,
    evolutions: [],
    artifacts: [],
    kills: 0,
    mutationStage: 0,
    invulnerableTimer: 0,
    contactDamageCooldown: 0,
    resonanceCharge: 0,
    resonanceEventActive: false,
    resonanceGeometryKey: 'none',
    resonanceGeometryNodes: [],
    resonanceLineBurst: 0,
    resonanceRingTimer: 0,
    resonanceRingPulseTimer: 0,
    resonanceRingCursor: 0,
    invulnUsed: false,
    shieldCharges: 0,
    shieldTimer: 0,
    dodgeTimer: 0,
    fireTrailTimer: 0,
    fireTrailCooldown: 0,
    blastCooldown: 0,
    teleportCooldown: 0,
    shieldCooldown: 0,
    minionCooldown: 0,
    lightningCooldown: 0,
    timestopCooldown: 0,
    darkritualCooldown: 0,
    overloadTimer: 0,
    timestopTimer: 0,
    swiftBootsTimer: 0,
    chaosOrbTimer: 0,
    chaosOrbBuff: null,
    chaosOrbBuffTimer: 0,
    teleportDamageBuffTimer: 0,
    fireCatalystTimer: 0,
    blinkHpCost: false,
    sphereXpAccumulator: 0,
    sphereUpgradeCount: 0,
    sphereProgression: { standard: 0, sniper: 0, shotgun: 0, chain: 0, aura: 0, orbital: 0, prism: 0, gravity: 0, pulse: 0, void: 0 },
    sphereBranches: {},
    sphereMods: { multishot: 0, pierce: 0, ricochet: 0, fire: 0, freeze: 0, poison: 0 },
    dashCooldown: 0,
    dashTimer: 0,
    dashDir: { x: 0, y: 0 },
    dashCount: 0,
    combo: 0,
    comboTimer: 0,
    comboMult: 1,
    buffTimer: 0,
    eliteKills: 0,
    chestOpens: 0,
    characterId,
    characterMasteryLevel,
    hunterMarkTarget: null,
    hunterMarkTimer: 0,
    hunterHitCount: 0,
    hunterHuntTarget: null,
    hunterHuntTimer: 0,
    hunterTrophyTimer: 0,
    engineerRelaySource: null,
    engineerRelayTimer: 0,
    alchemistCatalystTimer: 0,
  };
  return {
    player,
    spheres: [{
      pos: { x: 0, y: -95 },
      radius: BASE_SPHERE_RADIUS,
      damage: BASE_SPHERE_DAMAGE,
      attackDelay: BASE_SPHERE_DELAY,
      attackTimer: 0,
      rotation: 0,
      alive: true,
      networkDisabledTimer: 0,
      killsContribution: 0,
      formationHitCount: 0,
      resonancePulseTimer: 0,
      visualTier: 0,
      type: 'standard',
      auraTimer: 0,
    }],
    enemies: [],
    xpOrbs: [],
    healthPacks: [],
    particles: [],
    fireTrails: [],
    minions: [],
    lightnings: [],
    wave: 0,
    waveTimer: 3,
    waveEnemiesToSpawn: 0,
    waveSpawnTimer: 0,
    bossActive: false,
    bossDefeated: 0,
    time: 0,
    paused: false,
    gameOver: false,
    pendingUpgrade: null,
    levelUpPity: { ability: 0, sphere: 0, modifier: 0 },
    pendingArtifact: null,
    pendingStella: false,
    stellaClaims: 0,
    stellaLegendaryClaims: 0,
    stats: { time: 0, wave: 0, enemiesKilled: 0, goldEarned: 0 },
    screenShake: 0,
    bossArrow: null,
    flashText: null,
    keys: {},
    mouse: { x: 0, y: 0, down: false },
    formationMemory: null,
    worldWidth: 2400,
    worldHeight: 2400,
    mapTheme,
    camera: { x: 0, y: 0 },
    activeKeyMap: {},
    sphereProjectiles: [],
    artifactPickupPending: false,
    pendingSphereUpgrade: null,
    damageNumbers: [],
    chests: [],
    runes: [],
    difficulty: difficulty,
    evolutionsThisRun: 0,
    selectedSphereType: 'standard',
    shopUpgrades: { ...shop.upgrades },
    runSeed,
    rngState,
  };
}

function getCharacterMaxHpMultiplierForId(id: CharacterId): number {
  return 1 + CHARACTER_DEFS[id].baseModifiers.maxHp;
}
