import type { GameState, Vec, EnemyRole } from './engineTypes';
import type { BossType } from './gameData';

export type RegionId='resonance_basin'|'spectral_rift';
export type RegionMode='stabilization'|'endless';
export type RegionChallengeId='none'|'fractured_network'|'overload'|'low_gravity'|'mirror_tide'|'volatile_core'|'phase_drift';
export type RegionPoiType='resonance_cache'|'breach_node'|'echo_relay'|'lost_signal'|'elite_nest'|'rupture'|'boss_trace';
export interface RegionPocket{id:string;name:{ru:string;en:string};center:Vec;radius:number;ecology:'flow'|'swarm'|'pressure'|'fracture'|'hollow';accent:string}
export interface RegionPoi{id:number;type:RegionPoiType;pos:Vec;radius:number;alive:boolean;major:boolean;expiresAt:number}
export interface RegionChallenge{id:RegionChallengeId;name:{ru:string;en:string};desc:{ru:string;en:string}}
export interface RegionConfig{id:RegionId;name:{ru:string;en:string};subtitle:{ru:string;en:string};accent:string;pockets:readonly RegionPocket[];challenges:readonly RegionChallenge[];bossTimes:readonly number[];bossTypes:readonly BossType[];masteryChallenges:readonly {id:string;name:{ru:string;en:string};desc:{ru:string;en:string}}[];lore:readonly {id:string;title:{ru:string;en:string};text:{ru:string;en:string}}[]}
export interface RegionState{id:RegionId;mode:RegionMode;pocketId:string;phaseId:number;phaseName:{ru:string;en:string};pois:RegionPoi[];nextPoiAt:number;nextBossAt:number;majorBossesSpawned:number;finalBossSpawned:boolean;finalBossDefeated:boolean;cleared:boolean;endlessUnlocked:boolean;challengeId:RegionChallengeId;challengeContractsCompleted:number;masteryChallengesCompleted:number;masteryGeometryTypes:string[];masteryDominantSeconds:number;loreDiscovered:string[];damageTaken:number;lastHp:number;regionGoldReward:number;regionXpReward:number}

export const REGION_STABILIZATION_SECONDS=1800,REGION_FINAL_PREP_SECONDS=1620;
const BASIN_POCKETS:readonly RegionPocket[]=[
{id:'axis',name:{ru:'ОСЕВОЙ УЗЕЛ',en:'AXIS NODE'},center:{x:0,y:0},radius:340,ecology:'flow',accent:'#39d8ff'},
{id:'glass',name:{ru:'СТЕКЛЯННЫЙ ПОТОК',en:'GLASS FLOW'},center:{x:520,y:-260},radius:330,ecology:'swarm',accent:'#7cf7d4'},
{id:'fracture',name:{ru:'РАЗЛОМ',en:'FRACTURE'},center:{x:500,y:430},radius:330,ecology:'fracture',accent:'#ff6b6b'},
{id:'hollow',name:{ru:'ПУСТОЙ КОНТУР',en:'HOLLOW CONTOUR'},center:{x:-480,y:430},radius:330,ecology:'hollow',accent:'#9b7cff'},
{id:'pressure',name:{ru:'ЗОНА ДАВЛЕНИЯ',en:'PRESSURE FIELD'},center:{x:-520,y:-300},radius:330,ecology:'pressure',accent:'#ffb84d'}];
const RIFT_POCKETS:readonly RegionPocket[]=[
{id:'prism',name:{ru:'ПРИЗМАТИЧЕСКИЙ СДВИГ',en:'PRISM SHIFT'},center:{x:0,y:0},radius:330,ecology:'flow',accent:'#7fe8ff'},
{id:'shoal',name:{ru:'ЗЕРКАЛЬНАЯ МЕЛЬ',en:'MIRROR SHOAL'},center:{x:520,y:-270},radius:320,ecology:'swarm',accent:'#d48cff'},
{id:'ember',name:{ru:'ТЛЕЮЩИЙ ИЗЛОМ',en:'EMBER FAULT'},center:{x:470,y:450},radius:330,ecology:'pressure',accent:'#ff9d63'},
{id:'silent',name:{ru:'ТИХАЯ РЕШЁТКА',en:'SILENT LATTICE'},center:{x:-500,y:430},radius:320,ecology:'fracture',accent:'#65f0cf'},
{id:'null',name:{ru:'НУЛЕВОЙ САД',en:'NULL GARDEN'},center:{x:-520,y:-290},radius:330,ecology:'hollow',accent:'#a78cff'}];

const BASIN_CHALLENGES:readonly RegionChallenge[]=[
{id:'fractured_network',name:{ru:'РАЗЛОМ СЕТИ',en:'FRACTURED NETWORK'},desc:{ru:'Каждые 45с случайная Сфера временно выпадает из Сети.',en:'Every 45s a random Sphere temporarily leaves the Network.'}},
{id:'overload',name:{ru:'ПЕРЕГРУЗКА',en:'OVERLOAD'},desc:{ru:'Враги быстрее и прочнее, но дают больше XP.',en:'Enemies are faster and tougher, but grant more XP.'}},
{id:'low_gravity',name:{ru:'НИЗКАЯ ГРАВИТАЦИЯ',en:'LOW GRAVITY'},desc:{ru:'Отбрасывание слабее, зато Core движется быстрее.',en:'Repulsion is weaker, while the Core moves faster.'}}];
const RIFT_CHALLENGES:readonly RegionChallenge[]=[
{id:'mirror_tide',name:{ru:'ЗЕРКАЛЬНЫЙ ПРИЛИВ',en:'MIRROR TIDE'},desc:{ru:'Каждые 36с ритм врагов переключается между скоростью и плотностью.',en:'Every 36s enemy rhythm alternates between speed and pressure.'}},
{id:'volatile_core',name:{ru:'НЕСТАБИЛЬНОЕ ЯДРО',en:'VOLATILE CORE'},desc:{ru:'Высокий Резонанс усиливает врагов, но ускоряет следующий резонансный цикл.',en:'High Resonance empowers enemies but accelerates the next Resonance cycle.'}},
{id:'phase_drift',name:{ru:'ФАЗОВЫЙ СДВИГ',en:'PHASE DRIFT'},desc:{ru:'Фазовые враги чаще проходят через строй, зато Core движется быстрее.',en:'Phase enemies breach the formation more often, while Core moves faster.'}}];

const BASIN_MASTERY=Object.freeze([{id:'geometry_triad',name:{ru:'ТРИ ГЕОМЕТРИИ',en:'GEOMETRY TRIAD'},desc:{ru:'Активировать три разных Geometry-состояния.',en:'Activate three different Geometry states.'}},{id:'dominant_hold',name:{ru:'УДЕРЖАНИЕ',en:'DOMINANT HOLD'},desc:{ru:'Сохранить Dominant Geometry активной не менее 60 секунд.',en:'Keep Dominant Geometry active for at least 60 seconds.'}},{id:'lean_network',name:{ru:'ТОНКАЯ СЕТЬ',en:'LEAN NETWORK'},desc:{ru:'Завершить Region с четырьмя или менее Spheres.',en:'Clear the Region with four or fewer Spheres.'}}] as const);
const RIFT_MASTERY=Object.freeze([{id:'phase_triad',name:{ru:'ТРИ СДВИГА',en:'PHASE TRIAD'},desc:{ru:'Активировать три разных Geometry-состояния в Разломе.',en:'Activate three different Geometry states in the Rift.'}},{id:'stable_resonance',name:{ru:'СТАБИЛЬНЫЙ РЕЗОНАНС',en:'STABLE RESONANCE'},desc:{ru:'Не допустить падения Резонанса ниже 25 более 60 секунд подряд.',en:'Keep Resonance above 25 for 60 consecutive seconds.'}},{id:'lean_network',name:{ru:'ТОНКАЯ СЕТЬ',en:'LEAN NETWORK'},desc:{ru:'Завершить Разлом с четырьмя или менее Spheres.',en:'Clear the Rift with four or fewer Spheres.'}}] as const);

const BASIN_LORE=[{id:'origin',title:{ru:'Первый сигнал',en:'First Signal'},text:{ru:'Бассейн не был построен. Он возник вокруг первого стабильного Echo.',en:'The Basin was not built. It formed around the first stable Echo.'}},{id:'fracture',title:{ru:'Трещина',en:'The Fracture'},text:{ru:'Сеть запоминает не только связи. Она запоминает разрывы.',en:'The Network remembers not only connections. It remembers breaks.'}},{id:'glass',title:{ru:'Стеклянный поток',en:'Glass Flow'},text:{ru:'Поток ускоряется, когда Core перестаёт сопротивляться его ритму.',en:'The flow accelerates when the Core stops resisting its rhythm.'}},{id:'warden',title:{ru:'Страж Стеллы',en:'Stella Warden'},text:{ru:'Кто-то оставил Стеллу не как награду, а как проверку.',en:'Someone left the Stella not as a reward, but as a test.'}},{id:'stabilization',title:{ru:'Стабилизация',en:'Stabilization'},text:{ru:'Регион не уничтожен. Он согласился на новую форму.',en:'The Region is not destroyed. It has accepted a new shape.'}}] as const;
const RIFT_LORE=[{id:'rift_birth',title:{ru:'Рождение Разлома',en:'Rift Birth'},text:{ru:'Разлом не расширяется. Он переставляет расстояния местами.',en:'The Rift does not expand. It rearranges distance itself.'}},{id:'mirror_signal',title:{ru:'Зеркальный сигнал',en:'Mirror Signal'},text:{ru:'В некоторых импульсах Echo отвечает раньше, чем получает вопрос.',en:'In some pulses the Echo answers before it receives the question.'}},{id:'null_garden',title:{ru:'Нулевой сад',en:'Null Garden'},text:{ru:'Здесь тишина имеет плотность. Сеть чувствует её как давление.',en:'Here silence has density. The Network feels it as pressure.'}},{id:'phase_wound',title:{ru:'Фазовая рана',en:'Phase Wound'},text:{ru:'Первый разлом оставил шов, который продолжает двигаться.',en:'The first fracture left a seam that still moves.'}},{id:'rift_warden',title:{ru:'Страж Разлома',en:'Rift Warden'},text:{ru:'Страж проверяет, способен ли Core сохранить форму.',en:'The Warden tests whether the Core can keep its shape.'}}] as const;

export const REGION_CONFIGS:readonly RegionConfig[]=[
{id:'resonance_basin',name:{ru:'РЕЗОНАНСНЫЙ БАССЕЙН',en:'RESONANCE BASIN'},subtitle:{ru:'ПЕРВЫЙ СТАБИЛЬНЫЙ ECHO',en:'THE FIRST STABLE ECHO'},accent:'#55e6c1',pockets:BASIN_POCKETS,challenges:BASIN_CHALLENGES,bossTimes:[480,960],bossTypes:['conductor','architect','stella_warden'],masteryChallenges:BASIN_MASTERY,lore:BASIN_LORE},
{id:'spectral_rift',name:{ru:'СПЕКТРАЛЬНЫЙ РАЗЛОМ',en:'SPECTRAL RIFT'},subtitle:{ru:'ЗОНА ПЕРЕПИСАННЫХ РАССТОЯНИЙ',en:'ZONE OF REWRITTEN DISTANCE'},accent:'#a78cff',pockets:RIFT_POCKETS,challenges:RIFT_CHALLENGES,bossTimes:[450,930],bossTypes:['null','aura','stella_warden'],masteryChallenges:RIFT_MASTERY,lore:RIFT_LORE}
] as const;

export const REGION_POCKETS=BASIN_POCKETS;
export const REGION_CHALLENGES=BASIN_CHALLENGES;
export const REGION_MASTERY_CHALLENGES=BASIN_MASTERY;
export const REGION_LORE=BASIN_LORE;
export const REGION_BOSS_TIMES=[480,960] as const;
export const REGION_POI_TYPES:readonly RegionPoiType[]=['resonance_cache','breach_node','echo_relay','lost_signal','elite_nest','rupture','boss_trace'];

export function getRegionConfig(id:RegionId='resonance_basin'):RegionConfig{return REGION_CONFIGS.find(x=>x.id===id)||REGION_CONFIGS[0]}
function key(id:RegionId,suffix:string){return `echo-sphere:region:${id}:${suffix}`}
export function isRegionAvailable(id:RegionId):boolean{return id==='resonance_basin'||loadRegionStabilized('resonance_basin')}
export function loadRegionChallengeCompletions(id:RegionId='resonance_basin'):RegionChallengeId[]{if(typeof localStorage==='undefined')return[];try{const raw=JSON.parse(localStorage.getItem(key(id,'challenges'))||'[]');const allowed=getRegionConfig(id).challenges.map(c=>c.id);return Array.isArray(raw)?raw.filter((v):v is RegionChallengeId=>allowed.includes(v as RegionChallengeId)):[]}catch{return[]}}
export function markRegionChallengeComplete(id:RegionChallengeId,regionId:RegionId='resonance_basin'):void{if(id==='none'||typeof localStorage==='undefined')return;localStorage.setItem(key(regionId,'challenges'),JSON.stringify(Array.from(new Set([...loadRegionChallengeCompletions(regionId),id]))))}
export function getRegionChallengeProgress(regionId:RegionId='resonance_basin'):number{return loadRegionChallengeCompletions(regionId).length}
export function loadRegionStabilized(id:RegionId='resonance_basin'):boolean{return typeof localStorage!=='undefined'&&localStorage.getItem(key(id,'stabilized'))==='1'}
export function persistRegionStabilized(v:boolean,id:RegionId='resonance_basin'):void{if(typeof localStorage!=='undefined')localStorage.setItem(key(id,'stabilized'),v?'1':'0')}
export function loadRegionEndlessUnlock(id:RegionId='resonance_basin'):boolean{return getRegionChallengeProgress(id)>=3&&typeof localStorage!=='undefined'&&localStorage.getItem(key(id,'endless'))==='1'}
export function persistRegionEndlessUnlock(v:boolean,id:RegionId='resonance_basin'):void{if(typeof localStorage!=='undefined')localStorage.setItem(key(id,'endless'),v?'1':'0')}

export function createRegionState(regionId:RegionId='resonance_basin',mode:RegionMode='stabilization',challengeId:RegionChallengeId='none'):RegionState{const cfg=getRegionConfig(regionId);return{id:regionId,mode,pocketId:cfg.pockets[0].id,phaseId:0,phaseName:{ru:'ОРИЕНТАЦИЯ',en:'ORIENTATION'},pois:[],nextPoiAt:70,nextBossAt:cfg.bossTimes[0],majorBossesSpawned:0,finalBossSpawned:false,finalBossDefeated:false,cleared:false,endlessUnlocked:loadRegionEndlessUnlock(regionId),challengeId,challengeContractsCompleted:0,masteryChallengesCompleted:0,masteryGeometryTypes:[],masteryDominantSeconds:0,loreDiscovered:[],damageTaken:0,lastHp:0,regionGoldReward:regionId==='spectral_rift'?360:250,regionXpReward:0}}
export function getRegionPocket(s:GameState):RegionPocket{const cfg=getRegionConfig(s.region?.id||'resonance_basin');return cfg.pockets.find(p=>p.id===s.region?.pocketId)||cfg.pockets[0]}
export function getRegionPhase(t:number){if(t<300)return{id:0,name:{ru:'ОРИЕНТАЦИЯ',en:'ORIENTATION'}};if(t<600)return{id:1,name:{ru:'ПЕРВЫЙ РЕЗОНАНС',en:'FIRST RESONANCE'}};if(t<900)return{id:2,name:{ru:'СПЕЦИАЛИЗАЦИЯ',en:'SPECIALIZATION'}};if(t<1500)return{id:3,name:{ru:'ЭСКАЛАЦИЯ',en:'ESCALATION'}};if(t<1620)return{id:4,name:{ru:'СХОДИМОСТЬ',en:'CONVERGENCE'}};return{id:5,name:{ru:'СТАБИЛИЗАЦИЯ',en:'STABILIZATION'}}}
function nextR(s:GameState){s.rngState=(Math.imul(s.rngState,1664525)+1013904223)>>>0;return s.rngState/4294967296}
export function getRegionEnemyRole(s:GameState,fallback:EnemyRole):EnemyRole{const pool:Record<RegionPocket['ecology'],EnemyRole[]>={flow:['grunt','ranged','charger','anchor'],swarm:['swarmer','splitter','scavenger','phase'],pressure:['tank_guard','ranged','sniper','healer'],fracture:['phase','disruptor','corruptor','charger'],hollow:['leech','bomber','anchor','tank_guard']};const list=pool[getRegionPocket(s).ecology];return list[Math.floor(nextR(s)*list.length)]||fallback}
export function getRegionEnemyMultipliers(s:GameState){const p=getRegionPocket(s),cfg=getRegionConfig(s.region?.id||'resonance_basin');const base={flow:{hp:1,speed:1,damage:1,xp:1},swarm:{hp:.82,speed:1.22,damage:.88,xp:1.05},pressure:{hp:1.28,speed:.86,damage:1.18,xp:1.22},fracture:{hp:.94,speed:1.1,damage:1.08,xp:1.15},hollow:{hp:1.08,speed:.96,damage:1.12,xp:1.18}}[p.ecology];if(cfg.id==='resonance_basin'&&s.region?.challengeId==='overload')return{hp:base.hp*1.18,speed:base.speed*1.12,damage:base.damage*1.08,xp:base.xp*1.15};if(cfg.id==='spectral_rift'){if(s.region?.challengeId==='mirror_tide'){const surge=Math.floor(s.time/36)%2===0;return surge?{hp:base.hp*.94,speed:base.speed*1.20,damage:base.damage*.94,xp:base.xp*1.08}:{hp:base.hp*1.18,speed:base.speed*.88,damage:base.damage*1.16,xp:base.xp*1.20};}if(s.region?.challengeId==='volatile_core'&&s.player.resonanceCharge>=70)return{hp:base.hp*1.12,speed:base.speed*1.06,damage:base.damage*1.12,xp:base.xp*1.10};}return base}
export function getRegionMovementMultiplier(s:GameState){return s.region?.id==='spectral_rift'&&(s.region.challengeId==='phase_drift'||s.region.challengeId==='volatile_core')?1.10:s.region?.challengeId==='low_gravity'?1.12:1}
export function getRegionRepulsionMultiplier(s:GameState){return s.region?.id==='spectral_rift'&&s.region.challengeId==='phase_drift'?.62:s.region?.challengeId==='low_gravity'?.55:1}
export function getRegionResonanceMultiplier(s:GameState){if(s.region?.id==='spectral_rift'&&s.region.challengeId==='volatile_core')return s.player.resonanceCharge>=70?1.28:1.12;return Math.sin(s.time/18)>.62?1.18:1}
const dirs:readonly Vec[]=[{x:0,y:-1},{x:.92,y:-.38},{x:.88,y:.48},{x:-.82,y:.55},{x:-.92,y:-.34}];
function spawnPoi(s:GameState){const id=(s.region?.pois.reduce((m,p)=>Math.max(m,p.id),0)||0)+1;const pockets=getRegionConfig(s.region?.id||'resonance_basin').pockets,pocket=pockets[(id+Math.floor(s.time/60))%pockets.length],d=dirs[id%dirs.length],type=REGION_POI_TYPES[(id-1)%REGION_POI_TYPES.length];s.region!.pois.push({id,type,pos:{x:pocket.center.x+d.x*pocket.radius*.62,y:pocket.center.y+d.y*pocket.radius*.62},radius:24,alive:true,major:type==='elite_nest'||type==='boss_trace',expiresAt:s.time+(type==='boss_trace'?45:70)})}
function getRegionLocale():'ru'|'en'{return typeof localStorage!=='undefined'&&localStorage.getItem('echosphere_lang')==='en'?'en':'ru'}
export function getRegionPocketBrief(pocket:RegionPocket):{ru:string;en:string}{switch(pocket.ecology){case'flow':return{ru:'ДАЛЬНИЕ ВРАГИ',en:'RANGED PRESSURE'};case'swarm':return{ru:'БЫСТРЫЙ РОЙ',en:'FAST SWARM'};case'pressure':return{ru:'ТАНКИ / СНАЙПЕРЫ',en:'TANKS / SNIPERS'};case'fracture':return{ru:'ФАЗОВЫЙ ПРОБОЙ',en:'PHASE BREACH'};default:return{ru:'БОМБАРДИРОВЩИКИ',en:'BOMBERS'}}}
export function updateRegion(s:GameState,dt:number){const r=s.region;if(!r||r.cleared||s.tutorialMode)return{spawnBoss:false,finalBoss:false,bossType:undefined as BossType|undefined};const cfg=getRegionConfig(r.id);r.lastHp=r.lastHp||s.player.hp;if(s.player.hp<r.lastHp)r.damageTaken+=r.lastHp-s.player.hp;r.lastHp=s.player.hp;const ph=getRegionPhase(s.time);r.phaseId=ph.id;r.phaseName=ph.name;const previousPocketId=r.pocketId,pocket=cfg.pockets.reduce((a:RegionPocket,b:RegionPocket)=>Math.hypot(b.center.x-s.player.pos.x,b.center.y-s.player.pos.y)<Math.hypot(a.center.x-s.player.pos.x,a.center.y-s.player.pos.y)?b:a,cfg.pockets[0]);r.pocketId=pocket.id;if(s.time>1&&previousPocketId!==pocket.id){const locale=getRegionLocale();s.flashText={text:getRegionPocketBrief(pocket)[locale],life:1.35,color:pocket.accent,kind:'boundary'}}if(s.time>=r.nextPoiAt){spawnPoi(s);r.nextPoiAt+=38}r.pois=r.pois.filter(p=>p.alive&&p.expiresAt>s.time);if(r.mode==='stabilization'){const bt=cfg.bossTimes[r.majorBossesSpawned];if(bt!==undefined&&s.time>=bt&&!s.bossActive){r.majorBossesSpawned++;return{spawnBoss:true,finalBoss:false,bossType:cfg.bossTypes[Math.min(r.majorBossesSpawned-1,cfg.bossTypes.length-1)]}}if(!r.finalBossSpawned&&s.time>=REGION_FINAL_PREP_SECONDS&&!s.bossActive){r.finalBossSpawned=true;return{spawnBoss:true,finalBoss:true,bossType:cfg.bossTypes[cfg.bossTypes.length-1]}}if(r.finalBossSpawned&&s.time>=REGION_STABILIZATION_SECONDS&&!s.bossActive){r.finalBossDefeated=true;r.cleared=true;persistRegionStabilized(true,r.id);if(r.challengeId!=='none')markRegionChallengeComplete(r.challengeId,r.id);const completed=getRegionChallengeProgress(r.id);r.endlessUnlocked=completed>=3;r.challengeContractsCompleted=r.challengeId==='none'?0:1;r.masteryChallengesCompleted=(r.masteryGeometryTypes.length>=3?1:0)+(r.masteryDominantSeconds>=60?1:0)+(s.spheres.filter(x=>x.alive).length<=4?1:0);r.regionGoldReward=(r.id==='spectral_rift'?360:250)+s.player.eliteKills*5+s.bossDefeated*35;r.regionXpReward=Math.max(1,s.player.level*24);persistRegionEndlessUnlock(completed>=3,r.id);s.flashText={text:r.id==='spectral_rift'?'RIFT STABILIZED':'REGION STABILIZED',life:2.4,color:cfg.accent}}}else if(s.time>=r.nextBossAt&&!s.bossActive){r.nextBossAt+=150;return{spawnBoss:true,finalBoss:false,bossType:cfg.bossTypes[Math.min(r.majorBossesSpawned++,cfg.bossTypes.length-1)]}}const dom=s.networkFrame?.network.dominantFormation?.type;if(dom){if(!r.masteryGeometryTypes.includes(dom))r.masteryGeometryTypes.push(dom);if(s.networkFrame?.network.dominantFormation?.active!==false)r.masteryDominantSeconds+=dt}if(r.id==='resonance_basin'&&r.challengeId==='fractured_network'&&Math.floor(s.time/45)>Math.floor((s.time-dt)/45)){const c=s.spheres.filter(x=>x.alive&&x.networkDisabledTimer<=0);if(c.length){c[Math.floor(nextR(s)*c.length)].networkDisabledTimer=2.2;s.flashText={text:'NETWORK FRACTURE',life:.8,color:'#ff6b6b'}}}return{spawnBoss:false,finalBoss:false,bossType:undefined as BossType|undefined}}
export function collectRegionPoi(s:GameState):RegionPoiType|null{const p=s.region?.pois.find(x=>x.alive&&Math.hypot(x.pos.x-s.player.pos.x,x.pos.y-s.player.pos.y)<=x.radius+18);if(!p)return null;p.alive=false;if(s.region&&!s.region.loreDiscovered.includes(p.type))s.region.loreDiscovered.push(p.type);return p.type}
