import type { GameState, Vec, EnemyRole } from './engineTypes';
export type RegionMode='stabilization'|'endless';
export type RegionChallengeId='none'|'fractured_network'|'overload'|'low_gravity';
export type RegionPoiType='resonance_cache'|'breach_node'|'echo_relay'|'lost_signal'|'elite_nest'|'rupture'|'boss_trace';
export interface RegionPocket{id:string;name:{ru:string;en:string};center:Vec;radius:number;ecology:'flow'|'swarm'|'pressure'|'fracture'|'hollow';accent:string}
export interface RegionPoi{id:number;type:RegionPoiType;pos:Vec;radius:number;alive:boolean;major:boolean;expiresAt:number}
export interface RegionChallenge{id:RegionChallengeId;name:{ru:string;en:string};desc:{ru:string;en:string}}
export interface RegionState{id:'resonance_basin';mode:RegionMode;pocketId:string;phaseId:number;phaseName:{ru:string;en:string};pois:RegionPoi[];nextPoiAt:number;nextBossAt:number;majorBossesSpawned:number;finalBossSpawned:boolean;finalBossDefeated:boolean;cleared:boolean;endlessUnlocked:boolean;challengeId:RegionChallengeId;challengeContractsCompleted:number;masteryChallengesCompleted:number;masteryGeometryTypes:string[];masteryDominantSeconds:number;loreDiscovered:string[];damageTaken:number;lastHp:number;regionGoldReward:number;regionXpReward:number}
export const REGION_STABILIZATION_SECONDS=1800,REGION_FINAL_PREP_SECONDS=1620;
export const REGION_BOSS_TIMES=[480,960] as const;
export const REGION_POI_TYPES:readonly RegionPoiType[]=['resonance_cache','breach_node','echo_relay','lost_signal','elite_nest','rupture','boss_trace'];
export const REGION_MASTERY_CHALLENGES=Object.freeze([
{id:'geometry_triad',name:{ru:'ТРИ ГЕОМЕТРИИ',en:'GEOMETRY TRIAD'},desc:{ru:'Активировать три разных Geometry-состояния.',en:'Activate three different Geometry states.'}},
{id:'dominant_hold',name:{ru:'УДЕРЖАНИЕ',en:'DOMINANT HOLD'},desc:{ru:'Сохранить Dominant Geometry активной не менее 60 секунд.',en:'Keep Dominant Geometry active for at least 60 seconds.'}},
{id:'lean_network',name:{ru:'ТОНКАЯ СЕТЬ',en:'LEAN NETWORK'},desc:{ru:'Завершить Region с четырьмя или менее Spheres.',en:'Clear the Region with four or fewer Spheres.'}}
] as const;
export const REGION_LORE=[
{id:'origin',title:{ru:'Первый сигнал',en:'First Signal'},text:{ru:'Бассейн не был построен. Он возник вокруг первого стабильного Echo.',en:'The Basin was not built. It formed around the first stable Echo.'}},
{id:'fracture',title:{ru:'Трещина',en:'The Fracture'},text:{ru:'Сеть запоминает не только связи. Она запоминает разрывы.',en:'The Network remembers not only connections. It remembers breaks.'}},
{id:'glass',title:{ru:'Стеклянный поток',en:'Glass Flow'},text:{ru:'Поток ускоряется, когда Core перестаёт сопротивляться его ритму.',en:'The flow accelerates when the Core stops resisting its rhythm.'}},
{id:'warden',title:{ru:'Страж Стеллы',en:'Stella Warden'},text:{ru:'Кто-то оставил Стеллу не как награду, а как проверку.',en:'Someone left the Stella not as a reward, but as a test.'}},
{id:'stabilization',title:{ru:'Стабилизация',en:'Stabilization'},text:{ru:'Регион не уничтожен. Он согласился на новую форму.',en:'The Region is not destroyed. It has accepted a new shape.'}}
] as const;
export const REGION_CHALLENGES:readonly RegionChallenge[]=[
{id:'fractured_network',name:{ru:'РАЗЛОМ СЕТИ',en:'FRACTURED NETWORK'},desc:{ru:'Каждые 45с случайная Сфера временно выпадает из Сети.',en:'Every 45s a random Sphere temporarily leaves the Network.'}},
{id:'overload',name:{ru:'ПЕРЕГРУЗКА',en:'OVERLOAD'},desc:{ru:'Враги быстрее и прочнее, но дают больше XP.',en:'Enemies are faster and tougher, but grant more XP.'}},
{id:'low_gravity',name:{ru:'НИЗКАЯ ГРАВИТАЦИЯ',en:'LOW GRAVITY'},desc:{ru:'Отбрасывание слабее, зато Core движется быстрее.',en:'Repulsion is weaker, while the Core moves faster.'}}];
export const REGION_POCKETS:readonly RegionPocket[]=[
{id:'axis',name:{ru:'ОСЕВОЙ УЗЕЛ',en:'AXIS NODE'},center:{x:0,y:0},radius:340,ecology:'flow',accent:'#39d8ff'},
{id:'glass',name:{ru:'СТЕКЛЯННЫЙ ПОТОК',en:'GLASS FLOW'},center:{x:520,y:-260},radius:330,ecology:'swarm',accent:'#7cf7d4'},
{id:'fracture',name:{ru:'РАЗЛОМ',en:'FRACTURE'},center:{x:500,y:430},radius:330,ecology:'fracture',accent:'#ff6b6b'},
{id:'hollow',name:{ru:'ПУСТОЙ КОНТУР',en:'HOLLOW CONTOUR'},center:{x:-480,y:430},radius:330,ecology:'hollow',accent:'#9b7cff'},
{id:'pressure',name:{ru:'ЗОНА ДАВЛЕНИЯ',en:'PRESSURE FIELD'},center:{x:-520,y:-300},radius:330,ecology:'pressure',accent:'#ffb84d'}];
const dirs:readonly Vec[]=[{x:0,y:-1},{x:.92,y:-.38},{x:.88,y:.48},{x:-.82,y:.55},{x:-.92,y:-.34}];
export function createRegionState(mode:RegionMode='stabilization',challengeId:RegionChallengeId='none'):RegionState{return{id:'resonance_basin',mode,pocketId:'axis',phaseId:0,phaseName:{ru:'ОРИЕНТАЦИЯ',en:'ORIENTATION'},pois:[],nextPoiAt:70,nextBossAt:480,majorBossesSpawned:0,finalBossSpawned:false,finalBossDefeated:false,cleared:false,endlessUnlocked:false,challengeId,challengeContractsCompleted:0,masteryChallengesCompleted:0,masteryGeometryTypes:[],masteryDominantSeconds:0,loreDiscovered:[],damageTaken:0,lastHp:0,regionGoldReward:250,regionXpReward:0}}
export function getRegionPocket(s:GameState):RegionPocket{return REGION_POCKETS.find(p=>p.id===s.region?.pocketId)||REGION_POCKETS[0]}
export function getRegionPhase(t:number){if(t<300)return{id:0,name:{ru:'ОРИЕНТАЦИЯ',en:'ORIENTATION'}};if(t<600)return{id:1,name:{ru:'ПЕРВЫЙ РЕЗОНАНС',en:'FIRST RESONANCE'}};if(t<900)return{id:2,name:{ru:'СПЕЦИАЛИЗАЦИЯ',en:'SPECIALIZATION'}};if(t<1500)return{id:3,name:{ru:'ЭСКАЛАЦИЯ',en:'ESCALATION'}};if(t<1620)return{id:4,name:{ru:'СХОДИМОСТЬ',en:'CONVERGENCE'}};return{id:5,name:{ru:'СТАБИЛИЗАЦИЯ',en:'STABILIZATION'}}}
function nextR(s:GameState){s.rngState=(Math.imul(s.rngState,1664525)+1013904223)>>>0;return s.rngState/4294967296}
export function getRegionEnemyRole(s:GameState,fallback:EnemyRole):EnemyRole{const pool:Record<RegionPocket['ecology'],EnemyRole[]>={flow:['grunt','ranged','charger','anchor'],swarm:['swarmer','splitter','scavenger','phase'],pressure:['tank_guard','ranged','sniper','healer'],fracture:['phase','disruptor','corruptor','charger'],hollow:['leech','bomber','anchor','tank_guard']};const list=pool[getRegionPocket(s).ecology];return list[Math.floor(nextR(s)*list.length)]||fallback}
export function getRegionEnemyMultipliers(s:GameState){const b={flow:{hp:1,speed:1,damage:1,xp:1},swarm:{hp:.82,speed:1.22,damage:.88,xp:1.05},pressure:{hp:1.28,speed:.86,damage:1.18,xp:1.22},fracture:{hp:.94,speed:1.1,damage:1.08,xp:1.15},hollow:{hp:1.08,speed:.96,damage:1.12,xp:1.18}}[getRegionPocket(s).ecology];return s.region?.challengeId==='overload'?{hp:b.hp*1.18,speed:b.speed*1.12,damage:b.damage*1.08,xp:b.xp*1.15}:b}
export function getRegionMovementMultiplier(s:GameState){return s.region?.challengeId==='low_gravity'?1.12:1}
export function getRegionRepulsionMultiplier(s:GameState){return s.region?.challengeId==='low_gravity'?.55:1}
export function getRegionResonanceMultiplier(s:GameState){return Math.sin(s.time/18)>.62?1.18:1}
function spawnPoi(s:GameState){const id=(s.region?.pois.reduce((m,p)=>Math.max(m,p.id),0)||0)+1;const pocket=REGION_POCKETS[(id+Math.floor(s.time/60))%REGION_POCKETS.length],d=dirs[id%dirs.length],type=REGION_POI_TYPES[(id-1)%REGION_POI_TYPES.length];s.region!.pois.push({id,type,pos:{x:pocket.center.x+d.x*pocket.radius*.62,y:pocket.center.y+d.y*pocket.radius*.62},radius:24,alive:true,major:type==='elite_nest'||type==='boss_trace',expiresAt:s.time+(type==='boss_trace'?45:70)})}
export function updateRegion(s:GameState,dt:number){const r=s.region;if(!r||r.cleared||s.tutorialMode)return{spawnBoss:false,finalBoss:false};r.lastHp=r.lastHp||s.player.hp;if(s.player.hp<r.lastHp)r.damageTaken+=r.lastHp-s.player.hp;r.lastHp=s.player.hp;const ph=getRegionPhase(s.time);r.phaseId=ph.id;r.phaseName=ph.name;const pocket=REGION_POCKETS.reduce((a:RegionPocket,b:RegionPocket)=>Math.hypot(b.center.x-s.player.pos.x,b.center.y-s.player.pos.y)<Math.hypot(a.center.x-s.player.pos.x,a.center.y-s.player.pos.y)?b:a,REGION_POCKETS[0]);r.pocketId=pocket.id;if(s.time>=r.nextPoiAt){spawnPoi(s);r.nextPoiAt+=38}r.pois=r.pois.filter(p=>p.alive&&p.expiresAt>s.time);if(r.mode==='stabilization'){const bt=REGION_BOSS_TIMES[r.majorBossesSpawned];if(bt!==undefined&&s.time>=bt&&!s.bossActive){r.majorBossesSpawned++;return{spawnBoss:true,finalBoss:false}}if(!r.finalBossSpawned&&s.time>=REGION_FINAL_PREP_SECONDS&&!s.bossActive){r.finalBossSpawned=true;return{spawnBoss:true,finalBoss:true}}if(r.finalBossSpawned&&s.time>=REGION_STABILIZATION_SECONDS&&!s.bossActive){r.finalBossDefeated=true;r.cleared=true;r.endlessUnlocked=true;r.challengeContractsCompleted=r.challengeId==='none'?0:1;r.masteryChallengesCompleted=(r.masteryGeometryTypes.length>=3?1:0)+(r.masteryDominantSeconds>=60?1:0)+(s.spheres.filter(x=>x.alive).length<=4?1:0);r.regionGoldReward=250+s.player.eliteKills*4+s.bossDefeated*30;r.regionXpReward=Math.max(1,s.player.level*20);persistRegionEndlessUnlock(true);s.flashText={text:'REGION STABILIZED',life:2.4,color:'#55e6c1'}}}else if(s.time>=r.nextBossAt&&!s.bossActive){r.nextBossAt+=150;return{spawnBoss:true,finalBoss:false}}const dom=s.networkFrame?.network.dominantFormation?.type;if(dom){if(!r.masteryGeometryTypes.includes(dom))r.masteryGeometryTypes.push(dom);if(s.networkFrame?.network.dominantFormation?.active!==false)r.masteryDominantSeconds+=dt}if(r.challengeId==='fractured_network'&&Math.floor(s.time/45)>Math.floor((s.time-dt)/45)){const c=s.spheres.filter(x=>x.alive&&x.networkDisabledTimer<=0);if(c.length){c[Math.floor(nextR(s)*c.length)].networkDisabledTimer=2.2;s.flashText={text:'NETWORK FRACTURE',life:.8,color:'#ff6b6b'}}}return{spawnBoss:false,finalBoss:false}}
export function collectRegionPoi(s:GameState):RegionPoiType|null{const p=s.region?.pois.find(x=>x.alive&&Math.hypot(x.pos.x-s.player.pos.x,x.pos.y-s.player.pos.y)<=x.radius+18);if(!p)return null;p.alive=false;if(s.region&&!s.region.loreDiscovered.includes(p.type))s.region.loreDiscovered.push(p.type);return p.type}
export function persistRegionEndlessUnlock(v:boolean){if(typeof localStorage!=='undefined')localStorage.setItem('echo-sphere:region:resonance_basin:endless',v?'1':'0')}
export function loadRegionEndlessUnlock(){return typeof localStorage!=='undefined'&&localStorage.getItem('echo-sphere:region:resonance_basin:endless')==='1'}
