import type { CharacterId } from './characters';
import type { SphereType, AbilityType } from './gameData';

export type TowerEvolutionId = 'standard_resonator' | 'standard_singularity' | 'standard_swarm' | 'sniper_oracle' | 'sniper_assassin' | 'sniper_beacon' | 'shotgun_burst' | 'shotgun_cataclysm' | 'shotgun_hail' | 'chain_web' | 'chain_storm' | 'chain_leech' | 'aura_sanctum' | 'aura_gravity' | 'aura_overgrowth';
export type AbilityEvolutionId = 'echo_pulse' | 'echo_guard' | 'echo_jump' | 'echo_overdrive' | 'echo_drone' | 'echo_storm' | 'echo_phase';
export interface TowerUpgradeDef { level:number; name:{ru:string;en:string}; desc:{ru:string;en:string}; }
export interface TowerEvolutionDef { id:TowerEvolutionId; name:{ru:string;en:string}; desc:{ru:string;en:string}; }
export interface TowerEvolutionBranch extends TowerEvolutionDef { final:[TowerEvolutionDef,TowerEvolutionDef,TowerEvolutionDef]; }
export interface TowerDef { type:SphereType; name:{ru:string;en:string}; priority:Partial<Record<CharacterId,number>>; levels:TowerUpgradeDef[]; evolution4:TowerEvolutionDef; evolution7:TowerEvolutionDef; evolution4Choices:TowerEvolutionBranch[]; }
export interface AbilityProgressionDef { ability:AbilityType; levels:TowerUpgradeDef[]; evolution4:{id:AbilityEvolutionId;name:{ru:string;en:string};desc:{ru:string;en:string}}; evolution7:{id:AbilityEvolutionId;name:{ru:string;en:string};desc:{ru:string;en:string}}; }
const lv=(a:string,b:string,c:string):TowerUpgradeDef[]=>[{level:1,name:{ru:'Ядро',en:'Core'},desc:{ru:a,en:a}},{level:2,name:{ru:'Механизм',en:'Mechanism'},desc:{ru:b,en:b}},{level:3,name:{ru:'Настройка',en:'Tuning'},desc:{ru:c,en:c}},{level:4,name:{ru:'Эволюция I',en:'Evolution I'},desc:{ru:'Выбор одной из трёх веток',en:'Choose one of three branches'}},{level:5,name:{ru:'Контур',en:'Circuit'},desc:{ru:'Усиление выбранной ветки',en:'Strengthens the selected branch'}},{level:6,name:{ru:'Стабилизатор',en:'Stabilizer'},desc:{ru:'Усиление специальной механики',en:'Strengthens the special mechanic'}},{level:7,name:{ru:'Эволюция II',en:'Evolution II'},desc:{ru:'Финальная специализация',en:'Final specialization'}}];
const e=(id:TowerEvolutionId,ru:string,desc:string):TowerEvolutionDef=>({id,name:{ru,en:ru},desc:{ru:desc,en:desc}});
const br=(id:TowerEvolutionId,ru:string,desc:string,fin:[TowerEvolutionDef,TowerEvolutionDef,TowerEvolutionDef]):TowerEvolutionBranch=>({...e(id,ru,desc),final:fin});
const finals=(base:string,prefix:string,ids:[TowerEvolutionId,TowerEvolutionId,TowerEvolutionId]):[TowerEvolutionDef,TowerEvolutionDef,TowerEvolutionDef]=>ids.map((id,i)=>e(id,`${prefix} ${['I','II','III'][i]}`,`Финально усиливает ветку «${base}»`)) as [TowerEvolutionDef,TowerEvolutionDef,TowerEvolutionDef];
const tower=(type:SphereType,name:string,priority:Partial<Record<CharacterId,number>>,l:[string,string,string],branches:[TowerEvolutionBranch,TowerEvolutionBranch,TowerEvolutionBranch]):TowerDef=>({type,name:{ru:name,en:name},priority,levels:lv(...l),evolution4:branches[0],evolution7:branches[0].final[0],evolution4Choices:branches});
export const TOWER_PROGRESSION:Record<SphereType,TowerDef>={
 standard:tower('standard','Стандартная',{spherist:1,engineer:.9,berserker:.8,architect:.7,hunter:.4,alchemist:.4},['+15% урона','+1 пробитие','-10% задержки'],[br('standard_resonator','Резонатор','Каждое третье попадание выпускает импульс',finals('Резонатор','Гиперрезонатор',['standard_resonator','standard_singularity','standard_swarm'])),br('standard_singularity','Сингулярность','Попадания притягивают врагов',finals('Сингулярность','Коллапс',['standard_singularity','standard_resonator','standard_swarm'])),br('standard_swarm','Рой','Попадания выпускают осколки',finals('Рой','Каскад',['standard_swarm','standard_singularity','standard_resonator']))]),
 sniper:tower('sniper','Снайперская',{hunter:1,architect:.9,spherist:.4,engineer:.4,berserker:.3,alchemist:.3},['+25% урона','+15% дальности','+15% крита'],[br('sniper_oracle','Оракул','Критует отмеченные цели',finals('Оракул','Провидец',['sniper_oracle','sniper_assassin','sniper_beacon'])),br('sniper_assassin','Убийца','Усиливает урон по слабым целям',finals('Убийца','Казнь',['sniper_assassin','sniper_oracle','sniper_beacon'])),br('sniper_beacon','Маяк','Помечает цель для всей сети',finals('Маяк','Всевидящее око',['sniper_beacon','sniper_assassin','sniper_oracle']))]),
 shotgun:tower('shotgun','Дробовик',{berserker:1,alchemist:.8,spherist:.6,engineer:.4,hunter:.3,architect:.3},['+1 дробь','+20% урона вблизи','-12% разброса'],[br('shotgun_burst','Разрыв','Центральные дробины сильнее',finals('Разрыв','Катаклизм',['shotgun_burst','shotgun_cataclysm','shotgun_hail'])),br('shotgun_cataclysm','Осада','Тяжёлые пробивные снаряды',finals('Осада','Удар',['shotgun_cataclysm','shotgun_burst','shotgun_hail'])),br('shotgun_hail','Град','Много дополнительных снарядов',finals('Град','Ливень',['shotgun_hail','shotgun_burst','shotgun_cataclysm']))]),
 chain:tower('chain','Цепная',{spherist:1,hunter:.95,engineer:.9,alchemist:.8,architect:.5,berserker:.4},['+1 цель цепи','+10% урона цепи','+15% скорости перехода'],[br('chain_web','Паутина','Цели остаются связанными',finals('Паутина','Сеть Эха',['chain_web','chain_storm','chain_leech'])),br('chain_storm','Шторм','Каждый переход усиливает следующий',finals('Шторм','Разряд',['chain_storm','chain_web','chain_leech'])),br('chain_leech','Паразит','Цепь возвращает часть урона',finals('Паразит','Пожиратель',['chain_leech','chain_storm','chain_web']))]),
 aura:tower('aura','Аура',{engineer:1,alchemist:1,architect:.9,spherist:.7,hunter:.4,berserker:.4},['+20% радиуса ауры','-10% интервала импульса','+10% урона ауры'],[br('aura_sanctum','Святилище','Замедляет врагов и усиливает сферы',finals('Святилище','Эхо-святилище',['aura_sanctum','aura_gravity','aura_overgrowth'])),br('aura_gravity','Гравитация','Стягивает врагов к центру',finals('Гравитация','Сингулярность',['aura_gravity','aura_sanctum','aura_overgrowth'])),br('aura_overgrowth','Живая сеть','Усиливает сферы внутри ауры',finals('Живая сеть','Рост',['aura_overgrowth','aura_sanctum','aura_gravity']))])
};
const abilityLevels=(a:string,b:string,c:string)=>lv(a,b,c);
export const ABILITY_PROGRESSION:Partial<Record<AbilityType,AbilityProgressionDef>>={
 blast:{ability:'blast',levels:abilityLevels('+20% урона','+15% радиуса','-10% КД'),evolution4:{id:'echo_pulse',name:{ru:'Эхо-импульс',en:'Echo Pulse'},desc:{ru:'Волна проходит через сферы',en:'Pulse propagates through spheres'}},evolution7:{id:'echo_pulse',name:{ru:'Резонансный импульс',en:'Resonant Pulse'},desc:{ru:'Сферы усиливают волну',en:'Spheres amplify the pulse'}}},
 shield:{ability:'shield',levels:abilityLevels('+1 заряд','+20% прочности','+1с длительности'),evolution4:{id:'echo_guard',name:{ru:'Эхо-барьер',en:'Echo Guard'},desc:{ru:'Сферы принимают часть удара',en:'Spheres absorb part of hits'}},evolution7:{id:'echo_guard',name:{ru:'Бастион',en:'Bastion'},desc:{ru:'Щит создаёт защитное кольцо',en:'Shield creates a defensive ring'}}},
 teleport:{ability:'teleport',levels:abilityLevels('-2с КД','+1 точка','+20% дальности'),evolution4:{id:'echo_jump',name:{ru:'Эхо-прыжок',en:'Echo Jump'},desc:{ru:'Телепорт к сфере',en:'Teleport to a sphere'}},evolution7:{id:'echo_jump',name:{ru:'Разрыв пространства',en:'Space Break'},desc:{ru:'Прыжок оставляет волну',en:'Jump leaves a shockwave'}}},
 firetrail:{ability:'firetrail',levels:abilityLevels('+1с длительности','+20% урона','+20% ширины'),evolution4:{id:'echo_overdrive',name:{ru:'Перегрев',en:'Overdrive'},desc:{ru:'След усиливает огненные сферы',en:'Trail overcharges fire spheres'}},evolution7:{id:'echo_overdrive',name:{ru:'Термоядерный след',en:'Thermal Overdrive'},desc:{ru:'Перегрев распространяется по сети',en:'Overdrive propagates through network'}}},
 minion:{ability:'minion',levels:abilityLevels('+1 миньон','+20% урона','+2с жизни'),evolution4:{id:'echo_drone',name:{ru:'Эхо-дрон',en:'Echo Drone'},desc:{ru:'Миньон становится частью сети',en:'Minion joins the network'}},evolution7:{id:'echo_drone',name:{ru:'Рой Эха',en:'Echo Swarm'},desc:{ru:'Дроны создают узлы',en:'Drones create nodes'}}},
 lightning:{ability:'lightning',levels:abilityLevels('+1 цель','+20% урона','-15% КД'),evolution4:{id:'echo_storm',name:{ru:'Эхо-шторм',en:'Echo Storm'},desc:{ru:'Молния проводится через сферу',en:'Lightning conducts through a sphere'}},evolution7:{id:'echo_storm',name:{ru:'Грозовая сеть',en:'Storm Network'},desc:{ru:'Сеть создаёт последовательные разряды',en:'Network creates chained strikes'}}},
 timestop:{ability:'timestop',levels:abilityLevels('+0.5с остановки','+20% радиуса','-10% КД'),evolution4:{id:'echo_phase',name:{ru:'Фазовый разрыв',en:'Phase Break'},desc:{ru:'Сферы атакуют во время остановки',en:'Spheres attack during time stop'}},evolution7:{id:'echo_phase',name:{ru:'Вне времени',en:'Outside Time'},desc:{ru:'Сферы продлевают остановку',en:'Spheres extend time stop'}}},
};
export const CHARACTER_TOWER_PRIORITY:Record<CharacterId,SphereType[]>={spherist:['standard','chain'],hunter:['sniper','chain'],engineer:['aura','standard','chain'],berserker:['shotgun','standard'],alchemist:['aura','chain'],architect:['sniper','aura','standard']};
export const TOWER_ABILITY_SYNERGIES=[{tower:'standard',ability:'blast',name:{ru:'Резонансный удар',en:'Resonant Strike'},desc:{ru:'Импульс отскакивает от Standard-сфер',en:'Pulse bounces from Standard spheres'}},{tower:'sniper',ability:'teleport',name:{ru:'Маяк охотника',en:'Hunter Beacon'},desc:{ru:'Прыжок к Sniper отмечает элиту',en:'Jumping to Sniper marks an elite'}},{tower:'shotgun',ability:'shield',name:{ru:'Железный купол',en:'Iron Dome'},desc:{ru:'Щит выпускает дробовой залп',en:'Shield fires a shotgun burst'}},{tower:'chain',ability:'lightning',name:{ru:'Цепной разряд',en:'Chain Discharge'},desc:{ru:'Молния проходит по цепи',en:'Lightning travels along the chain'}},{tower:'aura',ability:'timestop',name:{ru:'Замкнутое время',en:'Closed Time'},desc:{ru:'Аура расширяется при остановке',en:'Aura expands during time stop'}},{tower:'standard',ability:'darkritual',name:{ru:'Жертвенный резонанс',en:'Sacrificial Resonance'},desc:{ru:'Ритуал удваивает Standard-урон',en:'Ritual doubles Standard damage'}},{tower:'aura',ability:'firetrail',name:{ru:'Пылающее святилище',en:'Burning Sanctum'},desc:{ru:'След заряжает ауру',en:'Trail charges the aura'}},{tower:'sniper',ability:'crit',name:{ru:'Око Эха',en:'Echo Eye'},desc:{ru:'Снайпер усиливает криты',en:'Sniper strengthens criticals'}}] as const;
export function towerPriority(character:CharacterId,type:SphereType){const list=CHARACTER_TOWER_PRIORITY[character]||[];const i=list.indexOf(type);return i<0?.25:1-i*.18;}
export function towerLevel(s:any,type:SphereType){return s.player.towerProgression?.[type]||0;}
export function towerModifiers(s:any,type:SphereType){const l=towerLevel(s,type);return {damage:1+l*.08+(l>=4?.12:0)+(l>=7?.18:0),radius:1+(l>=2?.05:0)+(l>=5?.06:0)+(l>=7?.08:0),delay:Math.max(.58,1-l*.045),pierce:l>=2?1:0,multishot:type==='shotgun'&&l>=1?1:0,chainTargets:type==='chain'?Math.max(1,l+1):0,auraRadius:l>=2?1.08:1,auraPulse:l>=4?.75:.5};}
