import type { GameState, SphereEntity, SphereProjectile, EnemyEntity, Particle, LightningBolt, MinionEntity } from './engine';
import type { SphereType } from './gameData';

type V3 = { x:number; y:number; z:number };
type Mat4 = Float32Array;

const DEG = Math.PI / 180;
const ASSET_BASE = '/art3d/';

function identity():Mat4 { return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]); }
function mul(a:Mat4,b:Mat4):Mat4 { const o=new Float32Array(16); for(let c=0;c<4;c++) for(let r=0;r<4;r++) o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3]; return o; }
function tr(x:number,y:number,z:number):Mat4 { const m=identity();m[12]=x;m[13]=y;m[14]=z;return m; }
function sc(x:number,y:number,z:number):Mat4 { const m=identity();m[0]=x;m[5]=y;m[10]=z;return m; }
function rx(a:number):Mat4 { const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]); }
function ry(a:number):Mat4 { const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1]); }
function rz(a:number):Mat4 { const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1]); }
function persp(fov:number,aspect:number,near:number,far:number):Mat4 { const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]); }
function lookAt(e:V3,c:V3,u:V3):Mat4 { let zx=e.x-c.x,zy=e.y-c.y,zz=e.z-c.z;let l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=u.y*zz-u.z*zy,xy=u.z*zx-u.x*zz,xz=u.x*zy-u.y*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;return new Float32Array([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*e.x+xy*e.y+xz*e.z),-(yx*e.x+yy*e.y+yz*e.z),-(zx*e.x+zy*e.y+zz*e.z),1]); }
function qmat(q:number[]):Mat4 { const [x,y,z,w]=q; return new Float32Array([1-2*y*y-2*z*z,2*x*y+2*w*z,2*x*z-2*w*y,0,2*x*y-2*w*z,1-2*x*x-2*z*z,2*y*z+2*w*x,0,2*x*z+2*w*y,2*y*z-2*w*x,1-2*x*x-2*y*y,0,0,0,0,1]); }
function trs(t:number[]|undefined,r:number[]|undefined,s:number[]|undefined):Mat4 { let m=identity();if(t)m=mul(m,tr(t[0],t[1],t[2]));if(r)m=mul(m,qmat(r));if(s)m=mul(m,sc(s[0],s[1],s[2]));return m; }

interface GLBPrimitive { position:Float32Array; normal:Float32Array; indices:Uint16Array|Uint32Array; color:[number,number,number]; emissive:[number,number,number]; }
interface GLBNode { name:string; local:Mat4; children:number[]; mesh:number|null; }
interface GLBAsset { nodes:GLBNode[]; meshes:GLBPrimitive[][]; roots:number[]; }

export class GLTFLoader {
  async load(url:string):Promise<GLBAsset>{
    const r=await fetch(url);if(!r.ok)throw new Error(`GLB ${url}: ${r.status}`);const b=await r.arrayBuffer();return this.parse(b);
  }
  private parse(buf:ArrayBuffer):GLBAsset{
    const dv=new DataView(buf);if(dv.getUint32(0,true)!==0x46546c67)throw new Error('Not a GLB');
    let off=12,json:any=null,bin=new Uint8Array();
    while(off<buf.byteLength){const len=dv.getUint32(off,true),type=dv.getUint32(off+4,true),data=buf.slice(off+8,off+8+len);off+=8+len;if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data));else if(type===0x004e4942)bin=new Uint8Array(data);}
    if(!json)throw new Error('GLB JSON missing');
    const read=(acc:any):any=>{const bv=json.bufferViews[acc.bufferView], base=(bv.byteOffset||0)+(acc.byteOffset||0), count=acc.count, ct=acc.componentType, comps=acc.type==='VEC3'?3:acc.type==='VEC2'?2:acc.type==='VEC4'?4:1;const C=ct===5126?Float32Array:ct===5125?Uint32Array:ct===5123?Uint16Array:Uint8Array;const step=C.BYTES_PER_ELEMENT*comps;const out=new C(count*comps);for(let i=0;i<count;i++)for(let j=0;j<comps;j++)out[i*comps+j]=new C(bin.buffer,bin.byteOffset+base+i*(bv.byteStride||step)+j*C.BYTES_PER_ELEMENT,1)[0];return out;};
    const materials=(json.materials||[]).map((m:any)=>({c:(m.pbrMetallicRoughness?.baseColorFactor||[1,1,1,1]).slice(0,3),e:m.emissiveFactor||[0,0,0]}));
    const meshes=(json.meshes||[]).map((m:any)=> (m.primitives||[]).map((p:any)=>{const pos=read(json.accessors[p.attributes.POSITION]);const normal=p.attributes.NORMAL!==undefined?read(json.accessors[p.attributes.NORMAL]):new Float32Array(pos.length);let idx:any;if(p.indices!==undefined){idx=read(json.accessors[p.indices]);}else{idx=new Uint32Array(pos.length/3);for(let i=0;i<idx.length;i++)idx[i]=i;}const mm=materials[p.material||0]||{c:[1,1,1],e:[0,0,0]};return{position:pos,normal,indices:idx,color:mm.c as [number,number,number],emissive:mm.e as [number,number,number]};}));
    const nodes=(json.nodes||[]).map((n:any)=>({name:n.name||'node',local:n.matrix?new Float32Array(n.matrix):trs(n.translation,n.rotation,n.scale),children:n.children||[],mesh:n.mesh===undefined?null:n.mesh}));
    const child=new Set<number>();nodes.forEach((n:GLBNode)=>n.children.forEach(i=>child.add(i)));const roots=nodes.map((_,i)=>i).filter(i=>!child.has(i));return{nodes,meshes,roots};
  }
}

interface GPUPrim extends GLBPrimitive { p:WebGLBuffer;n:WebGLBuffer;i:WebGLBuffer;count:number;indexType:number; }
interface GPUAsset { asset:GLBAsset; gpu:GPUPrim[][]; }

const VERT=`attribute vec3 a_position;attribute vec3 a_normal;uniform mat4 u_mvp;uniform mat4 u_model;varying vec3 v_n;varying vec3 v_w;void main(){vec4 w=u_model*vec4(a_position,1.0);v_w=w.xyz;v_n=normalize(mat3(u_model)*a_normal);gl_Position=u_mvp*vec4(a_position,1.0);}`;
const FRAG=`precision mediump float;uniform vec3 u_color;uniform vec3 u_emissive;uniform vec3 u_camera;uniform float u_time;uniform float u_alpha;uniform float u_glow;varying vec3 v_n;varying vec3 v_w;void main(){vec3 N=normalize(v_n);vec3 V=normalize(u_camera-v_w);float ndl=max(dot(N,normalize(vec3(-.35,.8,.45))),0.0);float fres=pow(1.0-max(dot(N,V),0.0),3.0);float pulse=.86+.14*sin(u_time*3.2+v_w.y*4.0);float rim=smoothstep(.2,1.0,fres);vec3 c=u_color*(.10+.90*ndl)+u_emissive*(.35+2.7*rim)*pulse*u_glow;c+=u_emissive*rim*0.35;gl_FragColor=vec4(c,u_alpha);}`;
const LINE_V=`attribute vec3 a_position;uniform mat4 u_mvp;void main(){gl_Position=u_mvp*vec4(a_position,1.0);}`;
const LINE_F=`precision mediump float;uniform vec3 u_color;uniform float u_alpha;uniform float u_time;void main(){float p=.82+.18*sin(u_time*8.0+gl_FragCoord.x*.02);gl_FragColor=vec4(u_color*p,u_alpha);}`;
const POST_V=`attribute vec2 a_position;varying vec2 v_uv;void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0,1);}`;
const POST_F=`precision mediump float;varying vec2 v_uv;uniform sampler2D u_scene;uniform vec2 u_texel;void main(){vec3 c=texture2D(u_scene,v_uv).rgb;vec3 b=vec3(0.0);for(int i=-4;i<=4;i++){vec2 o=vec2(float(i))*u_texel*2.0;b+=texture2D(u_scene,v_uv+o).rgb;}b/=9.0;float l=max(max(b.r,b.g),b.b);float k=smoothstep(.22,.7,l);gl_FragColor=vec4(c+b*k*1.15,1.0);}`;

export class Echo3DRenderer {
  private gl:WebGLRenderingContext;private program:WebGLProgram;private lineProgram:WebGLProgram;private postProgram:WebGLProgram;
  private loader=new GLTFLoader();private assets=new Map<string,GPUAsset>();private loading=new Map<string,Promise<void>>();
  private quad:WebGLBuffer;private sceneTex:WebGLTexture;private sceneFb:WebGLFramebuffer;private depth:WebGLRenderbuffer;
  private width=1;private height=1;
  constructor(private canvas:HTMLCanvasElement){const gl=canvas.getContext('webgl',{alpha:false,antialias:true,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL unavailable');this.gl=gl;this.program=this.make(VERT,FRAG);this.lineProgram=this.make(LINE_V,LINE_F);this.postProgram=this.make(POST_V,POST_F);this.quad=this.buf(new Float32Array([-1,-1,1,-1,-1,1,1,1]));this.sceneTex=gl.createTexture()!;this.sceneFb=gl.createFramebuffer()!;this.depth=gl.createRenderbuffer()!;gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.resize();void this.preload();}
  private make(v:string,f:string){const g=this.gl,s=(type:number,src:string)=>{const x=g.createShader(type)!;g.shaderSource(x,src);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(x)||'shader');return x;};const p=g.createProgram()!;g.attachShader(p,s(g.VERTEX_SHADER,v));g.attachShader(p,s(g.FRAGMENT_SHADER,f));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p)||'program');return p;}
  private buf(data:BufferSource){const b=this.gl.createBuffer()!;this.gl.bindBuffer(this.gl.ARRAY_BUFFER,b);this.gl.bufferData(this.gl.ARRAY_BUFFER,data,this.gl.STATIC_DRAW);return b;}
  private async preload(){for(const n of ['player_core','enemy_worker','enemy_guard','enemy_flyer','enemy_spider','enemy_slime','enemy_psionic','enemy_queen','boss_colony','boss_distortion','boss_singularity','projectile_energy','projectile_fire',...['standard','sniper','shotgun','chain','aura'].flatMap(t=>Array.from({length:7},(_:unknown,i:number)=>`sphere_${t}_t${i+1}`))]){try{await this.load(n)}catch(e){console.warn('[Echo3D]',e)}}}
  private async load(name:string){if(this.assets.has(name))return;if(this.loading.has(name))return this.loading.get(name)!;const p=this.loader.load(`${ASSET_BASE}${name}.glb`).then(a=>{const gpu=a.meshes.map(ms=>ms.map(m=>{const p=this.buf(m.position),n=this.buf(m.normal),i=this.gl.createBuffer()!;this.gl.bindBuffer(this.gl.ELEMENT_ARRAY_BUFFER,i);this.gl.bufferData(this.gl.ELEMENT_ARRAY_BUFFER,m.indices,this.gl.STATIC_DRAW);return{...m,p,n,i,count:m.indices.length,indexType:m.indices instanceof Uint32Array?this.gl.UNSIGNED_INT:m.indices instanceof Uint16Array?this.gl.UNSIGNED_SHORT:this.gl.UNSIGNED_BYTE};}));this.assets.set(name,{asset:a,gpu});});this.loading.set(name,p);return p;}
  private resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(this.canvas.clientWidth*d)),h=Math.max(1,Math.floor(this.canvas.clientHeight*d));if(w===this.width&&h===this.height)return;this.width=w;this.height=h;this.canvas.width=w;this.canvas.height=h;const g=this.gl;g.viewport(0,0,w,h);g.bindTexture(g.TEXTURE_2D,this.sceneTex);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,w,h,0,g.RGBA,g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.bindRenderbuffer(g.RENDERBUFFER,this.depth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT16,w,h);g.bindFramebuffer(g.FRAMEBUFFER,this.sceneFb);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.sceneTex,0);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.depth);g.bindFramebuffer(g.FRAMEBUFFER,null);}
  render(s:GameState){this.resize();const g=this.gl,t=s.time,p=s.player.pos;const aspect=this.width/Math.max(1,this.height),distance=Math.max(430,Math.min(760,Math.max(s.worldWidth,s.worldHeight)*.33));const eye={x:p.x,y:distance*.72,z:p.y+distance*.72},vp=mul(persp(48*DEG,aspect,1,2400),lookAt(eye,{x:p.x,y:0,z:p.y},{x:0,y:1,z:0}));g.bindFramebuffer(g.FRAMEBUFFER,this.sceneFb);g.viewport(0,0,this.width,this.height);g.clearColor(.002,.004,.009,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.drawGround(vp,t);for(const sp of s.spheres)if(sp.alive)this.drawSphere(sp,vp,t);for(const e of s.enemies)if(e.hp>0)this.drawEnemy(e,vp,t);this.drawPlayer(s,vp,t);for(const m of s.minions)this.drawMinion(m,vp,t);for(const q of s.sphereProjectiles)if(q.alive)this.drawProjectile(q,vp,t);for(const e of s.enemies)for(const q of e.bossProjectiles)if(q.alive)this.drawPointAsset('projectile_energy',q.pos.x,q.pos.y,q.radius*2,vp,t);for(const o of s.xpOrbs)if(o.alive)this.drawPointAsset('projectile_energy',o.pos.x,o.pos.y,o.radius*1.6,vp,t);for(const h of s.healthPacks)if(h.alive)this.drawPointAsset('projectile_fire',h.pos.x,h.pos.y,h.radius*1.8,vp,t);for(const f of s.fireTrails)if(f.life>0)this.drawPointAsset('projectile_fire',f.pos.x,f.pos.y,10+f.life*3,vp,t);this.drawNetwork(s.spheres,vp,t);this.drawLightnings(s.lightnings,vp,t);for(const pa of s.particles)if(pa.life>0)this.drawParticle(pa,vp,t);g.bindFramebuffer(g.FRAMEBUFFER,null);g.disable(g.DEPTH_TEST);g.useProgram(this.postProgram);g.bindBuffer(g.ARRAY_BUFFER,this.quad);const a=g.getAttribLocation(this.postProgram,'a_position');g.enableVertexAttribArray(a);g.vertexAttribPointer(a,2,g.FLOAT,false,0,0);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.sceneTex);g.uniform1i(g.getUniformLocation(this.postProgram,'u_scene'),0);g.uniform2f(g.getUniformLocation(this.postProgram,'u_texel'),1/this.width,1/this.height);g.drawArrays(g.TRIANGLE_STRIP,0,4);g.enable(g.DEPTH_TEST);}
  dispose(){this.assets.clear();}
  private modelForSphere(type:SphereType,tier:number){return `sphere_${type}_t${tier}`;}
  private drawSphere(s:SphereEntity,vp:Mat4,t:number){const tier=Math.max(1,Math.min(7,s.visualTier));this.drawAsset(this.modelForSphere(s.type,tier),s.pos.x,0,s.pos.y,Math.max(.5,s.radius/130),vp,t,`sphere:${tier}`,s.rotation+t*.12);}
  private drawEnemy(e:EnemyEntity,vp:Mat4,t:number){let n=e.isBoss?(String(e.bossType).toLowerCase().includes('dist')?'boss_distortion':String(e.bossType).toLowerCase().includes('sing')?'boss_singularity':'boss_colony'):(e.type==='fast'?'enemy_flyer':e.type==='tank'?'enemy_guard':e.type==='boss'?'enemy_queen':e.shape==='triangle'?'enemy_psionic':e.shape==='square'?'enemy_slime':'enemy_worker');const bob=e.type==='fast'?Math.sin(t*7+e.pos.x*.01)*.08:Math.sin(t*3+e.pos.y*.01)*.025;const bossPulse=e.isBoss?1+.045*Math.sin(t*2.6):1;this.drawAsset(n,e.pos.x,bob,e.pos.y,Math.max(.34,e.radius/18)*(e.isBoss?1.65:1)*bossPulse,vp,t,'enemy',e.rotation);}
  private drawPlayer(s:GameState,vp:Mat4,t:number){const pulse=1+.06*Math.sin(t*4);const tilt=Math.sin(t*2.2)*.035;this.drawAsset('player_core',s.player.pos.x,0,s.player.pos.y,1.25*pulse,vp,t,'player',t*.3+tilt);}
  private drawMinion(m:MinionEntity,vp:Mat4,t:number){const pulse=.46+.035*Math.sin(t*5+m.pos.x*.02);this.drawAsset('player_core',m.pos.x,0,m.pos.y,pulse,vp,t,'minion',m.rotation+t);}
  private drawProjectile(p:SphereProjectile,vp:Mat4,t:number){const n=p.effect==='fire'?'projectile_fire':'projectile_energy';this.drawAsset(n,p.pos.x,0,p.pos.y,Math.max(.22,p.radius/10),vp,t,'projectile',Math.atan2(p.vel.y,p.vel.x));}
  private drawPointAsset(name:string,x:number,z:number,size:number,vp:Mat4,t:number){this.drawAsset(name,x,0,z,Math.max(.12,size/16),vp,t,'fx',t*2);}
  private drawAsset(name:string,x:number,y:number,z:number,scale:number,vp:Mat4,t:number,tag:string,angle=0){const a=this.assets.get(name);if(!a){void this.load(name);return;}const root=mul(tr(x,y,z),mul(ry(angle),sc(scale,scale,scale)));for(const i of a.asset.roots)this.walk(a,i,root,vp,t,tag);}
  private walk(a:GPUAsset,ni:number,parent:Mat4,vp:Mat4,t:number,tag:string){const node=a.asset.nodes[ni];let local=node.local;if(node.name.includes('Leg_')){const m=(parseInt(node.name.split('_')[1]||'0',10)%2?1:-1);local=mul(local,rz(Math.sin(t*8+m)*.14));local=mul(local,rx(Math.sin(t*8+m)*.08));}if(node.name.includes('Ring_'))local=mul(local,ry(t*(node.name.endsWith('2')?.75:1.2)));if(node.name.includes('Core')||node.name.includes('VoidCore')||node.name.includes('SingularityCore')){const q=1+.055*Math.sin(t*4.5);local=mul(local,sc(q,q,q));}const world=mul(parent,local);if(node.mesh!==null)this.drawMesh(a.gpu[node.mesh],world,vp,t);for(const c of node.children)this.walk(a,c,world,vp,t,tag);}
  private drawMesh(ms:GPUPrim[],model:Mat4,vp:Mat4,t:number){const g=this.gl;for(const m of ms){g.useProgram(this.program);const ap=g.getAttribLocation(this.program,'a_position'),an=g.getAttribLocation(this.program,'a_normal');g.bindBuffer(g.ARRAY_BUFFER,m.p);g.enableVertexAttribArray(ap);g.vertexAttribPointer(ap,3,g.FLOAT,false,0,0);g.bindBuffer(g.ARRAY_BUFFER,m.n);g.enableVertexAttribArray(an);g.vertexAttribPointer(an,3,g.FLOAT,false,0,0);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,m.i);g.uniformMatrix4fv(g.getUniformLocation(this.program,'u_model'),false,model);g.uniformMatrix4fv(g.getUniformLocation(this.program,'u_mvp'),false,mul(vp,model));g.uniform3f(g.getUniformLocation(this.program,'u_color'),m.color[0],m.color[1],m.color[2]);g.uniform3f(g.getUniformLocation(this.program,'u_emissive'),m.emissive[0],m.emissive[1],m.emissive[2]);g.uniform3f(g.getUniformLocation(this.program,'u_camera'),0,500,500);g.uniform1f(g.getUniformLocation(this.program,'u_time'),t);g.uniform1f(g.getUniformLocation(this.program,'u_alpha'),1);g.uniform1f(g.getUniformLocation(this.program,'u_glow'),1.0);g.drawElements(g.TRIANGLES,m.count,m.indexType,0);}}
  private drawGround(vp:Mat4,t:number){for(let x=-800;x<=800;x+=80)this.line([x,-2.9,-800],[x,-2.9,800],vp,[.03,.12,.18],.24,t);for(let z=-800;z<=800;z+=80)this.line([-800,-2.9,z],[800,-2.9,z],vp,[.03,.12,.18],.24,t);}
  private drawNetwork(ss:SphereEntity[],vp:Mat4,t:number){for(let i=0;i<ss.length;i++)for(let j=i+1;j<ss.length;j++)if(ss[i].alive&&ss[j].alive)this.line([ss[i].pos.x,0,ss[i].pos.y],[ss[j].pos.x,0,ss[j].pos.y],vp,[.15,.65,1],.5+.2*Math.sin(t*5),t);}
  private drawLightnings(ls:LightningBolt[],vp:Mat4,t:number){for(const l of ls){const pts:number[]=[];for(let i=0;i<=8;i++){const q=i/8;pts.push(l.from.x+(l.to.x-l.from.x)*q+(i%2?Math.sin(t*50+i)*7:0),0,l.from.y+(l.to.y-l.from.y)*q+(i%2?Math.cos(t*47+i)*7:0));}this.polyline(pts,vp,[.3,.7,1],Math.max(.1,l.life),t);}}
  private drawParticle(p:Particle,vp:Mat4,t:number){this.drawPointAsset(p.size>18?'projectile_fire':'projectile_energy',p.pos.x,p.pos.y,p.size,vp,t);}
  private line(a:number[],b:number[],vp:Mat4,c:number[],alpha:number,t:number){this.polyline([...a,...b],vp,c,alpha,t);}
  private polyline(points:number[],vp:Mat4,c:number[],alpha:number,t:number){const g=this.gl,b=this.buf(new Float32Array(points));g.useProgram(this.lineProgram);const a=g.getAttribLocation(this.lineProgram,'a_position');g.bindBuffer(g.ARRAY_BUFFER,b);g.enableVertexAttribArray(a);g.vertexAttribPointer(a,3,g.FLOAT,false,0,0);g.uniformMatrix4fv(g.getUniformLocation(this.lineProgram,'u_mvp'),false,vp);g.uniform3f(g.getUniformLocation(this.lineProgram,'u_color'),c[0],c[1],c[2]);g.uniform1f(g.getUniformLocation(this.lineProgram,'u_alpha'),alpha);g.uniform1f(g.getUniformLocation(this.lineProgram,'u_time'),t);g.lineWidth(2);g.drawArrays(points.length===6?g.LINES:g.LINE_STRIP,0,points.length/3);g.deleteBuffer(b);}
}
export function createEcho3DRenderer(canvas:HTMLCanvasElement){return new Echo3DRenderer(canvas);}
