using System;
using System.Collections.Generic;

namespace EchoSphere.Core
{
    public readonly struct SphereEvolutionOption
    {
        public readonly string Id;
        public readonly string Name;
        public readonly string Description;
        public SphereEvolutionOption(string id, string name, string description) { Id = id; Name = name; Description = description; }
    }

    /// <summary>Names/descriptions sourced from new-desing/src/sphereProgression.ts.</summary>
    public static class SphereEvolutionCatalog
    {
        private static readonly Dictionary<SphereId, SphereEvolutionOption[]> Branches = new Dictionary<SphereId, SphereEvolutionOption[]>
        {
            [SphereId.Standard] = new SphereEvolutionOption[] { new SphereEvolutionOption("standard_resonator", "Резонатор", "Каждое третье попадание выпускает импульс; попадания также подпитывают Resonance"), new SphereEvolutionOption("standard_singularity", "Сингулярность", "Попадания притягивают врагов"), new SphereEvolutionOption("standard_swarm", "Рой", "Попадания выпускают осколки") },
            [SphereId.Sniper] = new SphereEvolutionOption[] { new SphereEvolutionOption("sniper_oracle", "Оракул", "Усиливает критический урон по отмеченным целям"), new SphereEvolutionOption("sniper_assassin", "Убийца", "Усиливает урон по слабым целям"), new SphereEvolutionOption("sniper_beacon", "Маяк", "Помечает цель для всей сети") },
            [SphereId.Shotgun] = new SphereEvolutionOption[] { new SphereEvolutionOption("shotgun_burst", "Разрыв", "Ближние попадания наносят повышенный урон и получают дополнительную дробь"), new SphereEvolutionOption("shotgun_cataclysm", "Осада", "Тяжёлые пробивные снаряды"), new SphereEvolutionOption("shotgun_hail", "Град", "Много дополнительных снарядов") },
            [SphereId.Chain] = new SphereEvolutionOption[] { new SphereEvolutionOption("chain_web", "Паутина", "Поражённые цели получают усиленное замедление"), new SphereEvolutionOption("chain_storm", "Шторм", "Каждый переход создаёт электрический всплеск и дополнительно заряжает Resonance"), new SphereEvolutionOption("chain_leech", "Паразит", "Цепь возвращает часть урона") },
            [SphereId.Aura] = new SphereEvolutionOption[] { new SphereEvolutionOption("aura_sanctum", "Святилище", "Замедляет врагов и удерживает их, усиливая ближайшие сферы"), new SphereEvolutionOption("aura_gravity", "Гравитация", "Стягивает врагов к центру"), new SphereEvolutionOption("aura_overgrowth", "Живая сеть", "Усиливает сферы внутри ауры") },
            [SphereId.Orbital] = new SphereEvolutionOption[] { new SphereEvolutionOption("orbital_dance", "Танец", "Спутники вращаются быстрее, наносят урон при пересечении траектории и оставляют Afterimage-следы."), new SphereEvolutionOption("orbital_halo", "Ореол", "Каждый успешный проход орбиты дополнительно заряжает Resonance."), new SphereEvolutionOption("orbital_blade", "Клинок", "Спутники превращаются в боевые лезвия, отбрасывают поражённых и могут оставлять Afterimage-следы.") },
            [SphereId.Prism] = new SphereEvolutionOption[] { new SphereEvolutionOption("prism_split", "Расщепление", "Луч после попадания делится на дополнительные лучи по другим целям."), new SphereEvolutionOption("prism_spectrum", "Спектр", "Луч передаёт активный статусный эффект, усиливает реакции и дополнительно заряжает Resonance."), new SphereEvolutionOption("prism_mirror", "Зеркало", "Связанные сферы создают отражённые лучи, повторяющие основной удар.") },
            [SphereId.Gravity] = new SphereEvolutionOption[] { new SphereEvolutionOption("gravity_well", "Колодец", "Притяжение становится постоянным: чем ближе враг к центру, тем сильнее его тянет."), new SphereEvolutionOption("gravity_tide", "Прилив", "Поле плавно меняет силу притяжения и периодически создаёт обратную волну."), new SphereEvolutionOption("gravity_collapse", "Коллапс", "Собранные в плотную группу враги получают дополнительный урон от сжатия.") },
            [SphereId.Pulse] = new SphereEvolutionOption[] { new SphereEvolutionOption("pulse_wave", "Волна", "Каждый импульс становится шире и отбрасывает врагов от сферы."), new SphereEvolutionOption("pulse_resonator", "Резонатор", "Импульсы подпитывают Resonance и усиливают сеть при активной геометрии."), new SphereEvolutionOption("pulse_burst", "Вспышка", "После основной волны возникает дополнительный разряд по центру.") },
            [SphereId.Void] = new SphereEvolutionOption[] { new SphereEvolutionOption("void_hunger", "Голод", "Урон растёт по мере потери здоровья целью; Corrupt дополнительно усиливает последующие попадания."), new SphereEvolutionOption("void_reaper", "Жнец", "Убийства Void возвращают HP и создают осколки пустоты для продолжения атаки."), new SphereEvolutionOption("void_execution", "Экзекуция", "Слабые цели получают шанс на мгновенное добивание, а атаки получают Phase-пробитие; финальная форма повышает порог исполнения.") },
        };

        private static readonly Dictionary<string, SphereEvolutionOption[]> Finals = new Dictionary<string, SphereEvolutionOption[]>
        {
            ["standard_resonator"] = new SphereEvolutionOption[] { new SphereEvolutionOption("standard_resonator_final_1", "Резонатор • Импульс", "Каждое третье попадание создаёт усиленный импульс вокруг цели: 65% урона, радиус 115."), new SphereEvolutionOption("standard_resonator_final_2", "Резонатор • Отбой", "Каждое третье попадание создаёт импульс по площади: 45% урона в радиусе 100 и отбрасывает ближайших врагов."), new SphereEvolutionOption("standard_resonator_final_3", "Резонатор • Срыв", "Каждое третье попадание создаёт импульс: 35% урона в радиусе 90 и замедляет ближайших врагов на 0.8 с.") },
            ["standard_singularity"] = new SphereEvolutionOption[] { new SphereEvolutionOption("standard_singularity_final_1", "Сингулярность • Сжатие", "Попадание сильнее стягивает ближайших врагов и удерживает цель замедленной на 1.2 с."), new SphereEvolutionOption("standard_singularity_final_2", "Сингулярность • Стазис", "Попадание удерживает цель замедленной дольше, до 1.8 с, усиливая контроль плотной группы."), new SphereEvolutionOption("standard_singularity_final_3", "Сингулярность • Коллапс", "Попадание сильнее стягивает врагов; цели ниже 50% HP получают +15% урона.") },
            ["standard_swarm"] = new SphereEvolutionOption[] { new SphereEvolutionOption("standard_swarm_final_1", "Рой • Охотничий осколок", "После попадания выпускает один осколок, который ищет ближайшую другую цель."), new SphereEvolutionOption("standard_swarm_final_2", "Рой • Перекрёстный огонь", "После попадания создаёт два боковых осколка по расходящимся траекториям."), new SphereEvolutionOption("standard_swarm_final_3", "Рой • Осколочная сеть", "После попадания создаёт три осколка, расходящихся веером и насыщащих зону вокруг цели.") },
            ["sniper_oracle"] = new SphereEvolutionOption[] { new SphereEvolutionOption("sniper_oracle_final_1", "Оракул • Критический фокус", "Крит по отмеченной цели наносит +50% урона."), new SphereEvolutionOption("sniper_oracle_final_2", "Оракул • Резонансный прицел", "Крит по отмеченной цели наносит +30% урона, а каждое попадание по отмеченной цели дополнительно заряжает Resonance."), new SphereEvolutionOption("sniper_oracle_final_3", "Оракул • Взрывной крит", "Крит по отмеченной цели наносит +22% урона, дополнительно задевает врагов рядом с целью и получает усиление Execute по целям ниже 30% HP.") },
            ["sniper_assassin"] = new SphereEvolutionOption[] { new SphereEvolutionOption("sniper_assassin_final_1", "Убийца • Метка казни", "Атаки по целям ниже 45% HP получают усиление добивания и устанавливают короткую метку казни."), new SphereEvolutionOption("sniper_assassin_final_2", "Убийца • Приговор", "Цели ниже 20% HP получают мощный финальный удар; при добивании следующая цель ниже 35% HP становится приоритетной."), new SphereEvolutionOption("sniper_assassin_final_3", "Убийца • Кровавый след", "Добивание слабой цели восстанавливает HP и выпускает охотничий импульс к ближайшей другой цели.") },
            ["sniper_beacon"] = new SphereEvolutionOption[] { new SphereEvolutionOption("sniper_beacon_final_1", "Маяк • Якорный", "Помеченная цель замедляется сильнее, а зона контроля вокруг неё получает усиливающийся эффект Anchor."), new SphereEvolutionOption("sniper_beacon_final_2", "Маяк • Прожектор", "Метка держится дольше, распространяет контроль на более широкую область и усиливает урон маркировки."), new SphereEvolutionOption("sniper_beacon_final_3", "Маяк • Сетевой", "Метка и Anchor работают вместе, распространяя замедление на область вокруг цели.") },
            ["shotgun_burst"] = new SphereEvolutionOption[] { new SphereEvolutionOption("shotgun_burst_final_1", "Разрыв • Ближний", "При дистанции до 150 наносится +30% урона и атака получает ещё 2 дополнительных снаряда."), new SphereEvolutionOption("shotgun_burst_final_2", "Разрыв • Осадный", "При дистанции до 180 наносится +50% урона."), new SphereEvolutionOption("shotgun_burst_final_3", "Разрыв • Ударный", "При дистанции до 150 наносится +22% урона, атака получает ещё 2 дополнительных снаряда, а цели ближе 90 дополнительно замедляются.") },
            ["shotgun_cataclysm"] = new SphereEvolutionOption[] { new SphereEvolutionOption("shotgun_cataclysm_final_1", "Осада • Осколочный взрыв", "Попадание создаёт взрыв радиусом 60, наносящий соседним врагам 45% урона; взрыв получает Shatter."), new SphereEvolutionOption("shotgun_cataclysm_final_2", "Осада • Тяжёлый взрыв", "Попадание создаёт большой взрыв радиусом 85, наносящий соседним врагам 65% урона и получает Impact."), new SphereEvolutionOption("shotgun_cataclysm_final_3", "Осада • Удерживающий взрыв", "Попадание создаёт взрыв радиусом 55 с 35% вторичного урона, Shatter/Impact и замедляет поражённых врагов.") },
            ["shotgun_hail"] = new SphereEvolutionOption[] { new SphereEvolutionOption("shotgun_hail_final_1", "Град • Осколочный", "Попадание с шансом создаёт круг из 6 осколков вокруг цели, насыщая ближайшую зону."), new SphereEvolutionOption("shotgun_hail_final_2", "Град • Плотный", "Каждый срабатывающий град выпускает 8 осколков и добавляет два снаряда к следующему залпу."), new SphereEvolutionOption("shotgun_hail_final_3", "Град • Охотничий", "Осколки выбирают ближайшие разные цели и расходятся к ним, превращая град в направленный веер охоты.") },
            ["chain_web"] = new SphereEvolutionOption[] { new SphereEvolutionOption("chain_web_final_1", "Паутина • Якорная", "Цепь усиливает замедление цели, а Anchor дополнительно удерживает её в зоне контроля."), new SphereEvolutionOption("chain_web_final_2", "Паутина • Статическая", "Цепь дольше удерживает замедление и получает шанс дополнительно перекинуть статический разряд на соседнюю цель."), new SphereEvolutionOption("chain_web_final_3", "Паутина • Парализующая", "Anchor и статический разряд работают вместе, превращая цепь в плотную зону контроля.") },
            ["chain_storm"] = new SphereEvolutionOption[] { new SphereEvolutionOption("chain_storm_final_1", "Шторм • Дуговой", "Переходы создают дополнительные дуговые удары по области вокруг каждой цели."), new SphereEvolutionOption("chain_storm_final_2", "Шторм • Резонансный", "Переходы подпитывают Resonance и заставляют следующий разряд проходить глубже по сети."), new SphereEvolutionOption("chain_storm_final_3", "Шторм • Разрядный цикл", "Каждый третий переход запускает отдельный разряд к ближайшей новой цели, создавая второй контур цепи.") },
            ["chain_leech"] = new SphereEvolutionOption[] { new SphereEvolutionOption("chain_leech_final_1", "Паразит • Кровоток", "Каждое попадание возвращает часть нанесённого урона в HP."), new SphereEvolutionOption("chain_leech_final_2", "Паразит • Сбор урожая", "Убийства цепной сферой возвращают HP."), new SphereEvolutionOption("chain_leech_final_3", "Паразит • Хищный цикл", "Попадания лечат, убийства лечат сильнее, а цели ниже 40% HP получают дополнительный урон.") },
            ["aura_sanctum"] = new SphereEvolutionOption[] { new SphereEvolutionOption("aura_sanctum_final_1", "Святилище • Холод", "Аура дольше и сильнее замедляет врагов в зоне."), new SphereEvolutionOption("aura_sanctum_final_2", "Святилище • Удержание", "Аура получает более сильный Anchor и удерживает врагов до 2 с."), new SphereEvolutionOption("aura_sanctum_final_3", "Святилище • Контроль", "Freeze и Anchor работают вместе, а сама аура получает +12% урона.") },
            ["aura_gravity"] = new SphereEvolutionOption[] { new SphereEvolutionOption("aura_gravity_final_1", "Гравитация • Тяга", "Аура стягивает врагов к центру с усиленной силой притяжения."), new SphereEvolutionOption("aura_gravity_final_2", "Гравитация • Удержание", "Аура стягивает врагов и одновременно замедляет их, превращая центр в устойчивую зону удержания."), new SphereEvolutionOption("aura_gravity_final_3", "Гравитация • Удар", "Сильная тяга и Anchor объединяются; собранная группа получает усиленный импульсный урон.") },
            ["aura_overgrowth"] = new SphereEvolutionOption[] { new SphereEvolutionOption("aura_overgrowth_final_1", "Живая сеть • Ускоритель", "Сферы внутри ауры получают постоянное ускорение следующего цикла атак."), new SphereEvolutionOption("aura_overgrowth_final_2", "Живая сеть • Перелив", "Когда сфера внутри ауры атакует, ускорение передаётся следующей ближайшей сфере в сети."), new SphereEvolutionOption("aura_overgrowth_final_3", "Живая сеть • Синхрон", "Все сферы внутри ауры одновременно сокращают задержку и выпускают следующую атаку почти синхронно.") },
            ["orbital_dance"] = new SphereEvolutionOption[] { new SphereEvolutionOption("orbital_dance_final_1", "Танец • Эхо-след", "Попадания оставляют повторный след-удар позади траектории спутника."), new SphereEvolutionOption("orbital_dance_final_2", "Танец • Гиперцикл", "Орбитальный цикл ускоряется в 1.55 раза и расширяет окно попадания на траектории."), new SphereEvolutionOption("orbital_dance_final_3", "Танец • Рой", "К орбитали добавляется дополнительный спутник, создавая вторую траекторию пересечения.") },
            ["orbital_halo"] = new SphereEvolutionOption[] { new SphereEvolutionOption("orbital_halo_final_1", "Ореол • Резонанс", "Проход спутника дополнительно заряжает Resonance."), new SphereEvolutionOption("orbital_halo_final_2", "Ореол • Расширение", "Окно попадания спутников расширяется, делая орбитальный проход стабильнее."), new SphereEvolutionOption("orbital_halo_final_3", "Ореол • Защита", "Резонанс заряжается сильнее, а успешный орбитальный проход восстанавливает заряд щита.") },
            ["orbital_blade"] = new SphereEvolutionOption[] { new SphereEvolutionOption("orbital_blade_final_1", "Клинок • Удар", "Боевые лезвия получают усиление Impact и сильнее бьют по траектории."), new SphereEvolutionOption("orbital_blade_final_2", "Клинок • Эхо-след", "След лезвия получает эффект Afterimage, усиливая повторные атаки орбитали."), new SphereEvolutionOption("orbital_blade_final_3", "Клинок • Разрез сети", "Impact и Afterimage работают вместе, а урон лезвий возрастает ещё сильнее.") },
            ["prism_split"] = new SphereEvolutionOption[] { new SphereEvolutionOption("prism_split_final_1", "Расщепление • Веер", "Луч создаёт веер дополнительных направлений, покрывая несколько целей одновременно."), new SphereEvolutionOption("prism_split_final_2", "Расщепление • Пробой", "После расщепления основной луч сохраняет энергию и пробивает первую цель насквозь."), new SphereEvolutionOption("prism_split_final_3", "Расщепление • Отражение", "После расщепления лучи рикошетят и могут сменить цель после первого попадания.") },
            ["prism_spectrum"] = new SphereEvolutionOption[] { new SphereEvolutionOption("prism_spectrum_final_1", "Спектр • Пламя", "Призма получает огненный статус для боевых реакций."), new SphereEvolutionOption("prism_spectrum_final_2", "Спектр • Холод", "Призма получает замораживающий статус для боевых реакций."), new SphereEvolutionOption("prism_spectrum_final_3", "Спектр • Токсин", "Призма получает токсический статус для боевых реакций.") },
            ["prism_mirror"] = new SphereEvolutionOption[] { new SphereEvolutionOption("prism_mirror_final_1", "Зеркало • Рикошет", "Отражённый луч один раз меняет цель после первого попадания."), new SphereEvolutionOption("prism_mirror_final_2", "Зеркало • Двойной рикошет", "Отражённый луч проходит две смены цели, сохраняя отдельные траектории отражений."), new SphereEvolutionOption("prism_mirror_final_3", "Зеркало • Сетевое отражение", "Отражение передаёт луч через связанную сеть и может завершить маршрут на двух разных узлах.") },
            ["gravity_well"] = new SphereEvolutionOption[] { new SphereEvolutionOption("gravity_well_final_1", "Колодец • Якорь", "Сфера получает сильный сетевой якорь, удерживающий врагов в зоне притяжения."), new SphereEvolutionOption("gravity_well_final_2", "Колодец • Усиление тяги", "Сила притяжения дополнительно усиливается, увеличивая контроль центра."), new SphereEvolutionOption("gravity_well_final_3", "Колодец • Полный колодец", "Якорь и усиленная тяга работают вместе, превращая центр в стабильную контрольную точку.") },
            ["gravity_tide"] = new SphereEvolutionOption[] { new SphereEvolutionOption("gravity_tide_final_1", "Прилив • Обратный толчок", "Каждый импульс резко отбрасывает врагов от Гравитационной сферы."), new SphereEvolutionOption("gravity_tide_final_2", "Прилив • Стягивание", "Каждый импульс притягивает врагов к Гравитационной сфере и уплотняет группу."), new SphereEvolutionOption("gravity_tide_final_3", "Прилив • Маятник", "Импульсы чередуют притяжение и отбрасывание, формируя ритм контроля пространства.") },
            ["gravity_collapse"] = new SphereEvolutionOption[] { new SphereEvolutionOption("gravity_collapse_final_1", "Коллапс • Экзекуция", "Собранные враги получают более сильное добивание, когда их HP уже снижено."), new SphereEvolutionOption("gravity_collapse_final_2", "Коллапс • Сжатие", "Гравитационная тяга дополнительно усиливает плотность группы перед коллапсом."), new SphereEvolutionOption("gravity_collapse_final_3", "Коллапс • Нулевой импульс", "Экзекуция и сжатие работают вместе; плотная группа дополнительно получает импульсный взрыв.") },
            ["pulse_wave"] = new SphereEvolutionOption[] { new SphereEvolutionOption("pulse_wave_final_1", "Волна • Отбой", "Каждый импульс сильнее отбрасывает врагов от сферы."), new SphereEvolutionOption("pulse_wave_final_2", "Волна • Заморозка", "Импульс получает замораживающий статус и расширяет радиус волны."), new SphereEvolutionOption("pulse_wave_final_3", "Волна • Разрушение", "Отбрасывание и заморозка работают вместе, превращая волну в инструмент контроля.") },
            ["pulse_resonator"] = new SphereEvolutionOption[] { new SphereEvolutionOption("pulse_resonator_final_1", "Резонатор • Заряд", "Импульсы сильнее заряжают Resonance при активной геометрии."), new SphereEvolutionOption("pulse_resonator_final_2", "Резонатор • Удар", "Повышенный Resonance-синергический эффект дополняется усилением Impact для контроля врагов."), new SphereEvolutionOption("pulse_resonator_final_3", "Резонатор • Раскол", "Повышенный Resonance-синергический эффект дополняется Shatter для усиления боевого импульса.") },
            ["pulse_burst"] = new SphereEvolutionOption[] { new SphereEvolutionOption("pulse_burst_final_1", "Вспышка • Раскол", "Основной импульс получает усиление Shatter."), new SphereEvolutionOption("pulse_burst_final_2", "Вспышка • Удар", "Основной импульс получает усиление Impact и лучше отбрасывает врагов."), new SphereEvolutionOption("pulse_burst_final_3", "Вспышка • Двойной разряд", "Shatter и Impact работают вместе, а Burst создаёт дополнительную волну.") },
            ["void_hunger"] = new SphereEvolutionOption[] { new SphereEvolutionOption("void_hunger_final_1", "Голод • Порча", "Пустота получает усиление Corrupt для работы по ослабленным целям."), new SphereEvolutionOption("void_hunger_final_2", "Голод • Резонанс", "Порча сохраняется, а попадания дополнительно заряжают Resonance."), new SphereEvolutionOption("void_hunger_final_3", "Голод • Поглощение", "Порча сочетается с восстановлением HP от успешных убийств, а попадания по целям ниже 30% HP дополнительно усиливаются на 12%.") },
            ["void_reaper"] = new SphereEvolutionOption[] { new SphereEvolutionOption("void_reaper_final_1", "Жнец • Кровь", "Попадания и убийства сильнее поддерживают восстановление HP."), new SphereEvolutionOption("void_reaper_final_2", "Жнец • Урожай", "Убийства заметно сильнее лечат и поддерживают цикл Пустоты."), new SphereEvolutionOption("void_reaper_final_3", "Жнец • Пожирание", "Восстановление от попаданий и убийств объединяется, а добивание дополнительно создаёт больше осколков пустоты.") },
            ["void_execution"] = new SphereEvolutionOption[] { new SphereEvolutionOption("void_execution_final_1", "Экзекуция • Порог", "Шанс исполнения и усиление урона по ослабленным целям повышаются."), new SphereEvolutionOption("void_execution_final_2", "Экзекуция • Фаза", "Сфера получает Phase, добавляющий пробитие атакам."), new SphereEvolutionOption("void_execution_final_3", "Экзекуция • Абсолют", "Execute и Phase объединяются; Phase добавляет пробитие, а порог исполнения повышается до 30% HP.") },
        };

        public static IReadOnlyList<SphereEvolutionOption> GetBranches(SphereId id)
        {
            return Branches.TryGetValue(id, out var options) ? options : Array.Empty<SphereEvolutionOption>();
        }

        public static IReadOnlyList<SphereEvolutionOption> GetFinals(string branchId)
        {
            return branchId != null && Finals.TryGetValue(branchId, out var options) ? options : Array.Empty<SphereEvolutionOption>();
        }
    }
}
